### ISSUE TITLE
Add storage sdk methods to update flags

### ISSUE THREAD

**Issue by sisuresh** [stellar/rs-soroban-sdk#1037]
The current storage interface does not let you set/unset flags. We should add additional methods to update the flag field so users can set/unset the `NO_AUTOBUMP` flag.

**Comment by sisuresh** [comment]
As part of this, the `NO_AUTOBUMP` tests removed as part of https://github.com/stellar/stellar-core/pull/3824/commits/bef8df46049eb36964181dd8de1785d99d1b2276 should be added back in.

**Comment by SirTyson** [comment]
Closing, storage flags have been removed
