### ISSUE TITLE
Create MIGRATION.md file

### ISSUE THREAD

**Issue by ueco-jb** [stellar/rs-soroban-sdk#1048]
### What problem does your feature solve?
If there are breaking changes, users must spend sometimes a significant chunk of time to go through changelog and most often commits as well to see what has changed and what needs to be adjusted in code.

### What would you like to see?
Create a markdown file, where breaking changes would be described with examples before and after.

### What alternatives are there?
Having multiple users asking same questions on discord.

**Comment by leighmcculloch** [comment]
The project currently uses the GitHub Release to announce changes at each release, but admittedly the release notes do not contain great detail about breaking changes vs other types of changes.

For the most part I think folks go to docs.rs/soroban-sdk for docs for the repo.

What I've seen in some repos, and we might benefit, is that we can build docs in a module in the Rust files and then that'll be generated into the docs.rs docs. A win for that is that we'll be able to include examples that get checked by a compiler. It should even be possible for us to import the previous major version of the SDK with examples of any before and after compared.

We'd have a module like `_releasenotes`, and then submodules for each major release like `_releasenotes::v21`, which will then have breaking changes, new features, and examples where needed to teach folks new things to do.

I can take a first go at this for the upcoming v21 release.

@anupsdf @stellar/contract-committers @fnando Thoughts?

**Comment by leighmcculloch** [comment]
I've posted a change that does as suggested above:
- https://github.com/stellar/rs-soroban-sdk/pull/1248

**Comment by ueco-jb** [comment]
> Have you experienced the same pain since the first stable release?

Hey, not so anymore. As you mentioned, since the SDK are more stable it became managable.

**Comment by fnando** [comment]
@leighmcculloch the only thing that comes to mind is writing better commit messages with some sort of annotation that indicates what's happening right on the title (e.g. `[breaking|change|new|fix] TITLE`).

Either that or the more manual but curated changelog file.
