### ISSUE TITLE
`Env::from_snapshot` no longer creates an `Env` consistent with `Env::default`

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#1101]
### What version are you using?

`v20.0.0-rc2`

### What did you do?

Serialized an `Env` to a `LedgerSnapshot`, then reloaded it into an `Env`.

### What did you expect to see?

The `Env` loaded with the same state as if `Env::default()` had been called and the ledger state loaded, meaning auth recording is off, and a default base prng seed is set.

### What did you see instead?

An `Env` loaded with auth recording on and no default base prng seed.

### Discussion

It looks like when we added new behavior, and removed auth recording, in `Env::default`:
https://github.com/stellar/rs-soroban-sdk/blob/0992413f9b05e5bfb1f872bce99e89d9129b2e61/soroban-sdk/src/env.rs#L524-L532

We forgot to make the same changes in `Env::from_snapshot`:
https://github.com/stellar/rs-soroban-sdk/blob/0992413f9b05e5bfb1f872bce99e89d9129b2e61/soroban-sdk/src/env.rs#L1216-L1231

We should probably have `Env::from_snapshot` and `Env::default` share the same setup logic and the same storage type, where default is just an empty `LedgerSnapshot`.

**Comment by leighmcculloch** [comment]
@brson You're welcome to take this, especially if it's blocking your work.

**Comment by brson** [comment]
Yep. I will try to fix it.
