### ISSUE TITLE
Env::try_invoke_contract_check_auth requires contract ID as a BytesN<32> instead of as an Address

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#1109]
### What version are you using?

`20.0.0-rc2`

### What did you do?

Call `Env::try_invoke_contract_check_auth` with an `Address` containing a contract ID.

### What did you expect to see?

🥳 

### What did you see instead?

Compile error saying I need to pass a `BytesN<32>`.

### Discussion

Blocked by:
- https://github.com/stellar/rs-soroban-env/issues/1099

**Comment by sisuresh** [comment]
This has been resolved - https://github.com/stellar/rs-soroban-sdk/blob/10018d855f9d3e82553de3e1db3285dee35814a9/soroban-sdk/src/env.rs#L1156
