### ISSUE TITLE
Token's 'authorized' function within StellarAssetClient

### ISSUE THREAD

**Issue by fazzatti** [stellar/rs-soroban-sdk#1116]
When using the token clients, I just noticed the '_authorized_' function to read the status of an address authorization is under the StellarAssetInterface([line 160](https://github.com/stellar/rs-soroban-sdk/blob/24f9f746af237022fe0958f5dc796f19babd0887/soroban-sdk/src/token.rs#L160)) which bundles admin capabilities.

Since this is a read-only function that doesn't require authorization, shouldn't it be included in the regular token interface([line 24](https://github.com/stellar/rs-soroban-sdk/blob/24f9f746af237022fe0958f5dc796f19babd0887/soroban-sdk/src/token.rs#L24))?

I believe this would be more in line with the standard [Token Interface](https://soroban.stellar.org/docs/reference/interfaces/token-interface) and also more intuitive.

- **Direct reference**: https://github.com/stellar/rs-soroban-sdk/blob/24f9f746af237022fe0958f5dc796f19babd0887/soroban-sdk/src/token.rs#L200C5-L200C5

**Comment by leighmcculloch** [comment]
It looks like the documentation hasn't been updated. The authorized fn was removed from the token interface because it's Stellar Asset specific and a little too prescriptive for applying to all tokens that might be developed.

**Comment by leighmcculloch** [comment]
The current token interface is now defined here: https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0041.md. 

I've opened this issue on the docs for getting them updated:
- https://github.com/stellar/soroban-docs/issues/640#issue-1978005504

I'm closing this issue and we'll track fixing this in the above issue. Please comment on the issue if I haven't addressed the issue at hand.
