### ISSUE TITLE
Env::from_snapshot should do additional testutils setup?

### ISSUE THREAD

**Issue by brson** [stellar/rs-soroban-sdk#1127]
### What problem does your feature solve?

In many of my tests I use snapshots to destroy and reconstruct the Env from scratch to simulate the advancement of time, e.g.

```rust
fn reset_env(prev_env: &Env, advance_time: u64) -> Env {
    let mut snapshot = prev_env.to_snapshot();
    snapshot.sequence_number += 1;
    snapshot.timestamp = snapshot.timestamp.saturating_add(advance_time);

    let env = Env::from_snapshot(snapshot);
    env.budget().reset_unlimited();

    env
}
```

The reason I do this is because I want the most accurate emulation of what happens in production, with the Env being destroyed and recreated every transaction, and I don't _think_ the common approach of mutating the sequence_number and timestamp without destroying the whole Env does that. In particular I want to ensure that:

- events are cleared
- the internal memory of the Host is cleared of all old Vals

Completely recreating the Env is the obvious way to ensure it's clean for the next transaction.

(If I really should not be destroying and recreating the Env during tests let me know, but it seems reasonable).

---

I have recently discovered that this doesn't do what I expect: with testutils configured Env::default (default_with_testutils) enables several configurations for convenience that Env::from_snapshot does not do. It seems that since from_snapshot is also a testutils function for creating an Env, it might be appropriate for it to do the same setup steps as Env::default.

In particular, Env::default turns on debug diagnostics and sets the prng seed; while Env::from_snapshot does not:

```rust
    fn default_with_testutils() -> Env {

        // ... snip details ...

        let rf = Rc::new(EmptySnapshotSource());
        let storage = internal::storage::Storage::with_recording_footprint(rf);
        let budget = internal::budget::Budget::default();
        let env_impl = internal::EnvImpl::with_storage_and_budget(storage, budget.clone());
        env_impl
            .set_source_account(xdr::AccountId(xdr::PublicKey::PublicKeyTypeEd25519(
                xdr::Uint256(random()),
            )))
            .unwrap();
        env_impl
            .set_diagnostic_level(internal::DiagnosticLevel::Debug)
            .unwrap();
        env_impl.set_base_prng_seed([0; 32]).unwrap();
        let env = Env {
            env_impl,
            snapshot: None,
        };

        env.ledger().set(internal::LedgerInfo {
            protocol_version: 20,
            sequence_number: 0,
            timestamp: 0,
            network_id: [0; 32],
            base_reserve: 0,
            min_persistent_entry_ttl: 4096,
            min_temp_entry_ttl: 16,
            max_entry_ttl: 6_312_000,
        });

        env
    }

    pub fn from_snapshot(s: LedgerSnapshot) -> Env {
        let info = s.ledger_info();

        let rs = Rc::new(s.clone());
        let storage = internal::storage::Storage::with_recording_footprint(rs.clone());
        let budget = internal::budget::Budget::default();
        let env_impl = internal::EnvImpl::with_storage_and_budget(storage, budget.clone());
        env_impl.switch_to_recording_auth(true).unwrap();

        let env = Env {
            env_impl,
            snapshot: Some(rs.clone()),
        };
        env.ledger().set(info);
        env
    }
```

### What would you like to see?

Env::from_snapshot should also turn on debug diagnostics and the prng.

### What alternatives are there?

My assumptions here about how from_snapshot should work may just be wrong.

---
cc https://github.com/stellar/soroban-examples/issues/286#issuecomment-1788147675

**Comment by leighmcculloch** [comment]
I think this is the same as:
- #1101 
This is definitely a bug.

**Comment by brson** [comment]
Dupe.
