### ISSUE TITLE
Move arbitrary module into testutils module

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#1131]
The arbitrary module is only intended for use when testutils are enabled. We have most testutils organized under a testutils module. The arbitrary module seems to be the exception where it lives at the top-level.

Was there a reason we didn't want it to be inside testutils? @brson Do you remember?

If there's no reason, would anyone be opposed to moving it under testutils?

**Comment by brson** [comment]
No reason. I just hadn't considered putting it there. I'm ok with moving it.

There's one it soroban-env-common as well. If this one moves, that one seemingly should to, though I don't think there is a corresponding testutils mod there.

**Comment by brson** [comment]
It may also be reasonable to hide the `arbitrary` module completely and just reexport the few things it defines publicly from testutils.
