### ISSUE TITLE
Test snapshots assume 1 Env per test

### ISSUE THREAD

**Issue by brson** [stellar/rs-soroban-sdk#1156]
### What version are you using?

20.0.0-rc2 d5d373dc775d58daf7a6097705fa5a6dd517a8ed

---

Under `testutils`, when `Env` is dropped, it writes a snapshot to a file with the name of the running unit test. This single file assumes that there is only one `Env` constructed per test.

This hasn't affected me yet, but I do write tests that construct multiples `Env`s, and there appears to be a limitation here.

**Comment by leighmcculloch** [comment]
Could you share a test where this is happening?

In https://github.com/stellar/rs-soroban-sdk/commit/23c219b7571b526be601af6d1f72ce7056489d13, that introduced the test snapshots, it includes logic for multiple unique Env instances going into separate files.

**Comment by leighmcculloch** [comment]
A file number is appended which is incremented for every unique Env that drops:
https://github.com/stellar/rs-soroban-sdk/blob/23c219b7571b526be601af6d1f72ce7056489d13/soroban-sdk/src/env.rs#L1339-L1359

**Comment by leighmcculloch** [comment]
I realized we didn't actually have a test for this behavior though so I opened:
- https://github.com/stellar/rs-soroban-sdk/pull/1157

**Comment by brson** [comment]
Ah, I was wrong. Sorry for the noise.
