### ISSUE TITLE
Add back the ability to create Addresses from bytes arrays

### ISSUE THREAD

**Issue by kalepail** [stellar/rs-soroban-sdk#1186]
Not having the ability to create Addresses from an array makes it a bit tricky to check matches in events later on.

e.g.
```rust
#![cfg(test)]

use alloc::vec;
use std::println;

extern crate alloc;
extern crate std;

use crate::{Contract, ContractClient};
use soroban_sdk::{symbol_short, testutils::Logs, Address, Env, String};

#[test]
fn test() {
    let env = Env::default();

    // StrKey.encodeContract(Buffer.from('0808080808080808080808080808080808080808080808080808080808080808', 'hex'))
    let contract_address = Address::from_string(&String::from_str(&env, "CAEAQCAIBAEAQCAIBAEAQCAIBAEAQCAIBAEAQCAIBAEAQCAIBAEAQMCJ"));
    let contract_id = env.register_contract(&contract_address, Contract);
    let client = ContractClient::new(&env, &contract_id);

    client.run(&Some(symbol_short!("Aratta")), &None);

    let logs = env.logs().all();

    assert_eq!(logs.len(), 0);

    client.run(&Some(symbol_short!("NotAratta")), &None);

    let logs = env.logs().all();

    println!("{}", logs.join("\n"));

    assert_eq!(logs, vec!["[Diagnostic Event] contract:0808080808080808080808080808080808080808080808080808080808080808, topics:[log], data:\"Aratta\""]);
}
```

Discord context
https://discord.com/channels/897514728459468821/1183815654487363584

**Comment by leighmcculloch** [comment]
The issue here has that diagnostic events shouldn't output addresses as hex. There's an issue open for this:
- https://github.com/stellar/rs-soroban-env/issues/1049

I think we should resolve that issue rather than add from byte arrays back.

**Comment by leighmcculloch** [comment]
In the next protocol release and matching sdk release all cases that hex addresses were outputted have been replaced with C strkey addresses. So I think we should close this issue and not add more exposure of hex forms back. Please reopen if this is an incorrect approach.
