### ISSUE TITLE
Request: Disable test snapshot feature for individual tests

### ISSUE THREAD

**Issue by mootz12** [stellar/rs-soroban-sdk#1225]
### What problem does your feature solve?

The test snapshot feature causes tests to run significantly slower. While this isn't an issue for a typical unit test, I've encountered situations where I want to write a stress test that takes unreasonably long to run.

### What would you like to see?

An attribute or some configuration a developer can set to have the test snapshot feature disabled for a specific test or test suite.

### What alternatives are there?

None

**Comment by leighmcculloch** [comment]
I'm of adding an option to the env to toggle this behaviour. Something like this:

```rust
fn test() {
    let env = Env::new_with_config(EnvConfig { capture_snapshot_at_drop: false });
    ...
    // No test snapshot written at drop.
}
```

Default behaviour would be equivalent to:
```rust
fn test() {
    let env = Env::new_with_config(EnvConfig { capture_snapshot_at_drop: true });
    ...
    // Test snapshot written at drop.
}
```
or:
```rust
fn test() {
    let env = Env::new_with_config(EnvConfig::default());
    ...
    // Test snapshot written at drop.
}
```
or:
```rust
fn test() {
    let env = Env::default();
    ...
    // Test snapshot written at drop.
}
```

Feedback appreciated.

**Comment by mootz12** [comment]
This looks great!

I agree that we should keep `Env::default()` as-is.

**Comment by leighmcculloch** [comment]
I've opened a change incorporating the above design:
- https://github.com/stellar/rs-soroban-sdk/pull/1235

@mootz12 If you happen to want to try it out before it's merged, please leave feedback!
