### ISSUE TITLE
Test Bug: Temporary Storage 

### ISSUE THREAD

**Issue by mootz12** [stellar/rs-soroban-sdk#1232]
### What version are you using?

```
[dependencies]
soroban-sdk = { version = "20.3.2" }
```

### What did you do?

Used the test env to both read and set an expired temporary storage entry.

### What did you expect to see?

1. When the temporary storage entry is expired, the get call to return `None`
2. A successful response when I set a temporary storage entry after it has expired

### What did you see instead?

1. The old value was returned
2. A failure with:
```
   4: [Failed Diagnostic Event (not emitted)] contract:CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD2KM, topics:[error, Error(Storage, InternalError)], data:["accessing no-longer-live entry", 220, 600]
   5: [Diagnostic Event] topics:[fn_call, Bytes(0000000000000000000000000000000000000000000000000000000000000001), set_temp], data:[CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFCT4, 222, 120]
```

Reproduction: https://github.com/mootz12/temp-storage-repro

**Comment by mootz12** [comment]
Note: I was able to verify this is working as expected on Futurenet using the same contract depicted in the reproduction example.

The transactions showing this were all done with the following source account: `GCLVUQFX5SBMLCDPGMDRFQZQ5EL6C5WE2N6OU6KMZV63KT2CZTGOJQZX`

**Comment by dmkozh** [comment]
SDK emulates state archival/temp entry removal more precisely since version 21+, as demonstrated in the [example](https://github.com/stellar/soroban-examples/tree/main/ttl). Sorry for updating this so late as the issue should be long gone.
