### ISSUE TITLE
Add automated resource cost reports

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#1319]
### What problem does your feature solve?

For a developer who has invested in significant test coverage, they should be able to, through the execution of those tests, get a good signal for the costs their contract is expected require.

### What would you like to see?

An option when running tests, maybe enabled by default if there is no significant performance issue with having it enabled, where a summary of every contract function that was executed along with it's range of costs.

An option for a detailed view where costs are shown per test.

### What alternatives are there?

Developers can get this themselves on each test, but it's difficult to get that broad overview.

### Caveat

The budget in the unit tests is not as accurate to when txs are submitted, and this issue is probably of very low impact unless that accuracy is improved in the Soroban Env when simulating in tests.

**Comment by dmkozh** [comment]
This should be addressed now by https://github.com/stellar/rs-soroban-sdk/pull/1411
