### ISSUE TITLE
Snapshots being created when capture snapshot at drop is false

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#1408]
### What version are you using?

TODO

### What did you do?

@kalepail reports https://stellarfoundation.slack.com/archives/C04B02ABF37/p1733866453752649:

> ```rust
> env.set_config(EnvTestConfig {
>         capture_snapshot_at_drop: false,
>     });
> ```
> Is not being respected anymore. Snapshots are being created

### What did you expect to see?

Snapshots not be created when `capture_snapshot_at_drop` is `false`.

### What did you see instead?

Snapshots are being created

**Comment by leighmcculloch** [comment]
@kalepail Can you share an example where you see this happening, and can you report which SDK version you're using?

**Comment by kalepail** [comment]
Well, now I can't get it to replicate. Closing until I see it again. Sorry for the noise
