### ISSUE TITLE
Feature Request: support for `getLedgers` endpoint

### ISSUE THREAD

**Issue by shahnami** [stellar/rs-soroban-sdk#1415]
### What problem does your feature solve?

Implement method for the `getLedgers` endpoint introduced in Stellar RPC [v22.1.0](https://github.com/stellar/stellar-rpc/releases/tag/v22.1.0)

https://developers.stellar.org/docs/data/rpc/api-reference/methods/getLedgers

### What would you like to see?

A new method `get_ledgers` which takes the parameters: start sequence, [end sequence], [pagination options]

### What alternatives are there?

/

**Comment by leighmcculloch** [comment]
Hi @shahnami!

This SDK is the Rust Soroban SDK for building Soroban contracts, and contracts can't call the RPC because contracts can't make network requests.

Could you share a little more detail about what you're planning to do? What type of application will be calling the getLedgers method?

**Comment by shahnami** [comment]
> Hi [@shahnami](https://github.com/shahnami)!
> 
> This SDK is the Rust Soroban SDK for building Soroban contracts, and contracts can't call the RPC because contracts can't make network requests.
> 
> Could you share a little more detail about what you're planning to do? What type of application will be calling the getLedgers method?

Apologies, I somehow created this issue in the wrong repository. It was meant for: https://github.com/stellar/rs-stellar-rpc-client
