### ISSUE TITLE
Type Safety in Collections: Add functions for try_from_val checking all elements

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#177]
Idea 2:

- Have the SDK touch all components of incoming values.
- For Vecs, Maps, and Sets, this would involve fully iterating the collection.

_Originally posted by @leighmcculloch in https://github.com/stellar/rs-stellar-contract-sdk/issues/152#issuecomment-1165951863_

**Comment by leighmcculloch** [comment]
Dependent on #176 #175

**Comment by graydon** [comment]
Not going to do this.
