### ISSUE TITLE
Type: BigInt: Implement Ref-op-Ref

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-sdk#185]
### What problem does your feature solve?

Right now, doing math can necessitate many clones.

### What would you like to see?

Something like
```rust
impl<'a> Add for &'a BigInt {
    type Output = BigInt;
    fn add(self, rhs: Self) -> Self::Output {
        // ...
    }
}
```
but for every operator.

### What alternatives are there?

Continue using `clone`.

**Comment by leighmcculloch** [comment]
@jonjove Could you point me to some code that currently uses clone so I can understand what impact this is having and what this looks like?

**Comment by jonjove** [comment]
https://github.com/stellar/soroban-examples/blob/c1e0425e822b94a1dc189ed43edbda7b146841da/liquidity_pool/src/lib.rs#L267-L268

It's not hideous, but it's also not beautiful.

**Comment by leighmcculloch** [comment]
Yeah that's pretty bad. Copying here for inline reference:
```rust
let out_a = (balance_a.clone() * balance_shares.clone()) / total_shares.clone();
let out_b = (balance_b.clone() * balance_shares.clone()) / total_shares.clone();
```

If we make these ref-op-ref, will it look like this:
```rust
let out_a = (&balance_a * &balance_shares) / &total_shares;
let out_b = (&balance_b * &balance_shares) / &total_shares;
```
or
```rust
let out_a = (balance_a * balance_shares) / total_shares;
let out_b = (balance_b * balance_shares) / total_shares;
```

**Comment by leighmcculloch** [comment]
Unfortunately BigInt contains a reference to an Env which contains an `Rc<>`, so I don't think it can be Copy.

**Comment by jonjove** [comment]
Ah right. I was only thinking about the case when `Env` is empty. Then references are the only path I think.
