### ISSUE TITLE
Test: Support outputting/inspecting resource usage and measured execution cost

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#193]

**Comment by graydon** [comment]
I _think_ we already support this in the CLI, right? @leighmcculloch do you want this elsewhere, like via a test helper function or something? Or can we close this as done?

**Comment by leighmcculloch** [comment]
We support getting at the values. At some point I was thinking of adding our own macro, `contracttest` that preloaded an `Env` and after running the test would log any logs and output costs. This isn't required though, potentially an improvement for the future.

**Comment by MonsieurNicolas** [comment]
This should probably take advantage of the work that will be done as part of https://github.com/stellar/stellar-core/issues/3759 (and related issues in env)? Then it's just a matter of the CLI just consuming diagnostic events?

**Comment by leighmcculloch** [comment]
The SDK already has access to the spent budget. Developers can do this at the end, or anywhere in, a test and they'll get a print out:

```rust
env.budget().print();
```

I think we can close this issue.

It would be nice, I think, if we potentially add a `#[contracttest]` attribute folks can place on tests, where the test gets given an `Env` pre-created, and at the end of the tests logs are outputted, and the budget is outputted. But on the same note, you can get the same by also just doing the following, so the complexity of adding a test macro doesn't feel like the right tradeoff. This is mostly why I held off adding it.

```rust
env.budget().print();
env.logger().print();
```

@MonsieurNicolas Are you imagining that the SDK would have access to fees? That's the one thing it doesn't have yet.

**Comment by jayz22** [comment]
Closing this since the SDK already supports printing the budget. If we want to add the `#[contracttest]` feature mentioned above, feel to reopen.
