### ISSUE TITLE
Type: Vec,Map: Re-assess with gas measurements on basic use

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#202]
Several people have raised concerns with the design of Vec and Map that we need to reassess once we have a way to measure gas.

Questions that need to be answered:
- Does ser/der items as they are stored and retrieved more efficient than ser/der items all in one hit at the point in time they need to be stored?
- Should we have implementations of Vec and Map that ser/der entirely in a single pass? Would this be more appropriate for smaller collections, or inputs/outputs from functions? This would require the SDK to have an allocator most likely.
- Should Vec and Map slice internally or via the host? (see #189 #191)
- Are the use of Options or Results anywhere in the API an outsized cost?

**Comment by graydon** [comment]
I think you're using "ser/deser" here to refer partly to the conversion from a map/vec host object to a map/vec XDR value (before storage), but also partly using it to refer to the pointwise calls from guest to host to access or modify the map/vec? Those latter do not serialize or deserialize, though they do rebuild the map/vec on mutation, a pointwise _read_ is just pulling a single RawVal out of a vector of RawVals.

In terms of slicing, I .. lean towards not doing it and making the iterator type the only stateful collection-indexing object in the guest. I recognize that you would get a win if you made the slice operator form a lazy copy-with-an-offset and projected indexes through the offset but I think that's the only case that wins, and .. users can do that by hand if they care enough. It taxes every other code path with adding an almost-always-zero offset from any index and subtracting an almost-always-zero offset from any length.

In terms of options and results, I would make the main APIs return fewer of them (and panic on failure) and add APIs called `TryFoo` that return the more-optional versions.

**Comment by leighmcculloch** [comment]
The most important change for us to make is to rewrite the iterator to not use the slice. Having the slicing capability is fine I think and useful, however we shouldn't be using it to power the iterator. This work should be a pretty straight path for anyone who wants to pick it up.

Changing the Option/Result outputs is less clear / a little complex and not straight path work. We need to do some experiments, and then comparisons, as well as get input from a variety of folks on how those experiments fair. So it might be worth punting it for now, or at least separating it into its own issue.

**Comment by leighmcculloch** [comment]
I think we can close this issue because I think sufficient work has either already been done, or is already planned with specific issues opened:

I recently did a pass over both collection types and added a selection of functions for folks to make safety vs performance tradeoffs, so folks can go more performant for less safety, or more safety for less performance. That was done as part of https://github.com/stellar/rs-soroban-sdk/issues/379:
- https://github.com/stellar/rs-soroban-sdk/pull/961
- https://github.com/stellar/rs-soroban-sdk/pull/974
- https://github.com/stellar/rs-soroban-sdk/pull/980

We also recently improved the performance of Vec and Map iterators, which were the worse areas of performance issues in these types:
- #999 
- #1003 

We also plan to add _many functions to support bulk operations:
- #997

We also have plans to improve the performance of slicing vecs:
- https://github.com/stellar/rs-soroban-env/issues/871
