### ISSUE TITLE
Type Safety in Collections: Add new trait TryFromValDeep

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#209]
Idea 5:
- Add new trait `TryFromValDeep` with new Vec/Map types that implement it
- Impl TryFromValDeep on all primitive and SDK non-collection types
- Impl TryFromValDeep on all UDTs that do not contain host serialized Vec/Map types
- New Vec2/Map2 (better names obviously) types that parallel existing Vec/Map, but use fixed memory internals (noalloc)
- Encourage use of Vec2/Map2 for inputs/outputs unless Vec/Map have specific benefit
- Document clearly the risks of Vec/Map with unvalidated data

_Originally posted by @leighmcculloch in https://github.com/stellar/rs-stellar-contract-sdk/issues/152#issuecomment-1180052677_

**Comment by leighmcculloch** [comment]
Vec2/Map2 are likely to be #210.

**Comment by graydon** [comment]
I _think_ we're not going to do this. @leighmcculloch would you concur?

**Comment by leighmcculloch** [comment]
I think it would be ideal if we find a way to exhaustively unpack values coming into a contract as an input, otherwise I think this could be a footgun for contract developers. Alternatively, we should make it a best practice that you always iterate a Vec / Map and put this somewhere in the docs as a "Security Best Practices" type of thing.

@graydon Are you leaning towards the latter?

cc @C0x41lch0x41

**Comment by graydon** [comment]
@leighmcculloch I'm leaning towards not even telling users to do anything here, because in practice I think it's a non-issue. Evidence so far suggests users will be using UDTs for for any fixed-size structured data, which eagerly / deeply unpack themselves (thus avoiding any footgun), and for any variable-size data they'll usually be using separate contract-data ledger entries to avoid size limits and enable parallelism.

**Comment by leighmcculloch** [comment]
While UDTs do eagerly unpack, any Vec or Map contained inside a UDT will not. Maybe that's an uncommon usage though.

It's possible this should just be a warning on the Vec / Map types in the Rust docs. Wdyt?

**Comment by graydon** [comment]
I think that would be adequate. I don't actually think people are going to use manually-constructed (non-UDT) maps much at all. Maybe vecs?

**Comment by C0x41lch0x41** [comment]
> Alternatively, we should make it a best practice that you always iterate a Vec / Map and put this somewhere in the docs as a "Security Best Practices" type of thing.

@leighmcculloch what's your security concerns here? I thought the objects were allocated on the host side and guest code did not have access to the raw memory pointers.

**Comment by leighmcculloch** [comment]
When I looked at other ecosystems, I remember Near has the same issue and they do nothing about it, at least they didn't as far as I could tell, and at the time. But they did give their collections other names that naturally led me to 👀 reading up the docs to figure out what the collection was.

**Comment by C0x41lch0x41** [comment]
Ok thanks @leighmcculloch.
Is it something (code storing user provided Vec/Map without accessing the values) we could detect during compilation and raise a warning to the user?

**Comment by graydon** [comment]
> I tried that at some point and experimented with what it looked like. It felt like the resulting code experience was penalizing the developer in all the cases where this shouldn't be a problem

I'm interested to hear you say this. Can you say more? I don't think there are a lot of use cases for explicit vecs and maps in the first place (since users will use the contract data ledger entries for large data and UDTs for small data) and in the residual set of cases it seems to me this isn't any worse than the Java-pre-generics world of just doing a fallible-cast-on-extract if you even care about the extracted type -- not beautiful UI but hardly a showstopper, and an obvious site of fallibility in terms of the user mental model.

**Comment by leighmcculloch** [comment]
If I recall correctly it suffered the same footgun as the contract data interface, in that every location that accessed a value had to specify the type to convert into. Sounds harmless, but it's easy to mistakenly write u128 instead of i128. With contract data I've made the mistake of reading the wrong type that I wrote. Sounds silly, but once you do it, and once the compiler doesn't help you it feels a bit left field given the context of Rust typically being so type safe. I agree tests should always identify these things, but it can still be annoying to debug and get right, especially when writing smaller entries that are just a i128.

In terms of penalizing the developer, what I mean is if a developer has a UDT containing a Vec<i128>, and they store the UDT, their code is always going to end up storing the right thing and reading the right thing, if they constructed the Vec themselves. So that's convenient that they get that type safety if they've done the right thing.

I'm coming around to the idea of trying this again, but from a theoretical perspective the trade-offs one way or the other aren't clearly better if we drop the type.

We could collect feedback from others on a Vec vs Vec<T>?

**Comment by leighmcculloch** [comment]
Another example is that functions that return Vec<T> no longer communicate the type they return, and that is lost in contract interfaces. For example, this SEP just proposed would have `Vec` as the return type of the addresses function, instead of `Vec<Address>`.

https://github.com/stellar/stellar-protocol/pull/1354/files#diff-383ab319153392a019913f9e9d054d2781d5f96933bf640a3a37264e4b03f72dR69
