### ISSUE TITLE
Refactor derive_fn

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-sdk#266]
### What problem does your feature solve?

The function is extremely long, and it's getting hard to maintain.

### What would you like to see?

The function has a few conceptually separate parts which can be split into separate functions.

### What alternatives are there?

Leave it as is.

**Comment by leighmcculloch** [comment]
I'd like to see the parsing moved into a new type that implements `syn::Parse`. This macro then becomes two top level parts:
- Parse the input to produce the structured data we need. This Parse type is the only part that should produce errors. 
- Render the template. This part should be infallible.

Once that's done I think we can move each render component into it's own function.

I'd think we should do this after and not before #153.
