### ISSUE TITLE
Make contractimpl and derive_contract_function_set work with multiple traits

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-sdk#268]
### What problem does your feature solve?

There are several areas of code that have introduced a restriction on the number of `impl` blocks that can appear for a type that has `contractimpl`'s.

1. The `derive_contract_function_set` will try to impl the `ContractFunctionSet` repeatedly if there are multiple `contractimpl` for the same type.

2. The `contractclient` attribute that `contractimpl` adds to the impl will try and create multiple contract client types that all have the same name.

### What would you like to see?

It should be possible to define multiple `impl` blocks both for the inherent type and for traits for a struct that is being used as a contract implementation.

### What alternatives are there?

Use different types for each impl, but this leads to an imperfect setup for testing, since only a single ContractFunctionSet can currently be registered for a contract ID. It's possible we could support the registration of multiple ContractFunctionSets.

**Comment by leighmcculloch** [comment]
I had some discussions with folks in Rust Discord a couple times about the issue of storing and building state across multiple macro invocations. The linkme crate kept being suggested as a way to do it, https://github.com/dtolnay/linkme.

**Comment by leighmcculloch** [comment]
We are unlikely to solve this problem in the near term, so I'm removing this from any near term iterations.

**Comment by leighmcculloch** [comment]
We could support multiple traits inside a single proc-macro invocation such as:
```rust
contractimpl! {
    impl Contract {
    }

    impl Trait for Contract {
    }
}
```
