### ISSUE TITLE
Use standard feature names in contractimpl

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-sdk#269]
### What problem does your feature solve?

Need to pass in a lot of feature names to make things compile. No ecosystem standardization.

### What would you like to see?

The feature names are standard so developers get everything "for free" and the ecosystem always knows what to enable/disable.

### What alternatives are there?

N/A

**Comment by leighmcculloch** [comment]
This problem will be addressed by https://github.com/stellar/rs-soroban-sdk/pull/409.
