### ISSUE TITLE
Reconsider Sign Errors

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-sdk#315]
> I'd like to circle back on trying to remove the dependence on std::error::Error, because it's confusing to me that this is compatible with conversion errors from the SDK, given that the SDK doensn't support std. But if this works 👏🏻

_Originally posted by @leighmcculloch in https://github.com/stellar/rs-stellar-contract-sdk/pull/312#pullrequestreview-1050168272_

**Comment by leighmcculloch** [comment]
I understand why this was required now, and I don't think we need to do anything about it. Thanks.
