### ISSUE TITLE
Generated client could return Result

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-sdk#330]
We might want to return the `Result` given that the function will be used in testing, there's a good chance people will be asserting on the return value, and it is easy to assert on a `Result` which makes testing a bit clearer imo.

_Originally posted by @leighmcculloch in https://github.com/stellar/rs-stellar-contract-sdk/pull/316#discussion_r929395219_

**Comment by leighmcculloch** [comment]
This could use the assert on panic logic that @graydon added to Env.

**Comment by leighmcculloch** [comment]
This should use the assert on panic logic, but it should also handle the status returning functionality @graydon has talked about and plans to implement.

**Comment by leighmcculloch** [comment]
This issue is no longer relevant as the generated code no longer exists. In regards to this topic area, results are exposed in https://github.com/stellar/rs-soroban-sdk/pull/596 and https://github.com/stellar/rs-soroban-sdk/pull/601.
