### ISSUE TITLE
Re-evaluate Option<Result<...>> trade-offs

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-sdk#379]
```[tasklist]
### Tasks
- [x] Storage https://github.com/stellar/rs-soroban-sdk/pull/961
- [x] Set #979
- [x] Vec https://github.com/stellar/rs-soroban-sdk/pull/974
- [x] Map #980 
- [ ] Bytes
```

**Comment by leighmcculloch** [comment]
We can evaluate this from multiple fronts:

- Secure Coding – Does this meaningfully help developers write more secure code. Is the code more likely to do what the developer wants and expects.

- Ergonomics – How convenient is the code.

– Code Size – Does this trade-off too significantly on the code size generated. Is the code size noise, or significant?

– Instruction Count – Does this trade-off too significantly on the instructions executed.

I'm suspicious of the pattern as well, but I was also surprised to find that in a decent amount of the code I've updated adding it, the code already had safety checks and so the addition of the `Option<>` just moved logic around, and it didn't introduce new branches.

**Comment by graydon** [comment]
I'd lean (ergonomics-wise) towards making the normal cases return `Result<>` as they have to and adding `_try` cases that return `Result<Option<T>,E>` when it's less of an "error" and more of a partial function (eg. `Map::try_get`)

**Comment by leighmcculloch** [comment]
@graydon Are you suggesting lifting the Option::None into an error in the Result? This is what we had before what we had now and it felt cumbersome to maintain.

Or do you mean switch around the names of the functions, so the _unchecked function becomes the main one, and the main one becomes the try_ one?

**Comment by graydon** [comment]
@leighmcculloch the latter option -- we make the main path one that panics if surprised, and we give users a try path for handling the unusual cases if they care. We got feedback recently that this is a bit of an ergonomic sore spot for users. Do you feel strongly either way?

**Comment by leighmcculloch** [comment]
I think that sounds fine. If doing that, I think we should remove the _unchecked variations, which often are just confusing.

Instead of littering the type with 2x of every function, what if we have two types, `Vec` and `TryVec`. The former would just wrap the latter. `TryVec` would essentially be what we have. `Vec` would wrap it and call `.unwrap_optimized` on any `Result` value.

Would there be a performance downside to doing it that way?

We could hide `TryVec` in the docs for now, to see if anyone asks for this behavior, but to not advertise it. This would be better imo over making it private, since if someone shows up an needs it, private means there's no option until a future release to use it.

**Comment by leighmcculloch** [comment]
I'm imagining:
```rust
pub struct Vec<T>(TryVec<T>)

impl Vec<T> {
    pub fn get(&self, i: u32) -> Option<T>
```
```rust
#[doc(hidden)]
pub struct TryVec<T> {
    env: Env,
    obj: VecObject,
    _t: PhantomData<T>,
}

impl TryVec<T> {
    pub fn get(&self, i: u32) -> Option<Result<T, T::Error>>
```

**Comment by leighmcculloch** [comment]
We should also change the interface for `Storage::get` so that it doesn't return `Option<Result<>>`. This one is even less controversial because a contract controls the type that is set, and therefore a correctly written contract can guarantee the value's type. So I think it could be changed as follows, with no alternative:

```
pub fn get<K, V>(&self, key: &K) -> Option<V>
```

**Comment by graydon** [comment]
Discussed offline. Consensus:

Map is:
```
pub fn get(&self, k: K) -> Option<Result<V, V::Error>>
```
Map becomes:
```
pub fn get(&self, k: K) -> Option<V>
pub fn try_get(&self, k: K) -> Option<Result<V, V::Error>>
```
Vec is:
```
pub fn get(&self, i: u32) -> Option<Result<T, T::Error>>
```
Vec becomes:
```
pub fn get(&self, i: u32) -> Option<T>
pub fn try_get(&self, i: u32) -> Option<Result<T, T::Error>>
```

**Comment by graydon** [comment]
Also we add a `try_iterator` because the impl of `Debug` for the containers wants fallible results

**Comment by willemneal** [comment]
Personally `try_*` implies that the function returns a Result. So transpose makes more sense to me.

**Comment by leighmcculloch** [comment]
@graydon and I were debating this as well, however the only error case is that of conversation in the case that in the case that Option is Some. If we transpose we require users to handle a case that'll never happen, error when None. But regardless maybe transpose is more intuitive?

**Comment by leighmcculloch** [comment]
That would make the new API:

Map is:
```
pub fn get(&self, k: K) -> Option<Result<V, V::Error>>
```
Map becomes:
```
pub fn get(&self, k: K) -> Option<V>
pub fn try_get(&self, k: K) -> Result<Option<V>, V::Error>
```
Vec is:
```
pub fn get(&self, i: u32) -> Option<Result<T, T::Error>>
```
Vec becomes:
```
pub fn get(&self, i: u32) -> Option<T>
pub fn try_get(&self, i: u32) -> Result<Option<T>, T::Error>
```

**Comment by leighmcculloch** [comment]
I've added a task list to the top of this issue.

**Comment by leighmcculloch** [comment]
I've started this work for the `Vec` type in:
- https://github.com/stellar/rs-soroban-sdk/pull/974

At the first commit I've done the `get` family of functions. Please take a look and let me know what you think. I'll be continuing with the rest of the functions after a brief pause to allow for feedback.

**Comment by leighmcculloch** [comment]
@willemneal @graydon One place that `Result<Option<>>` doesn't work is in the iterator. Iterators by definition of their `next` function must have the `Option<>` on the outside. So the try iterator will have `next() -> Option<Result<T, _>>` and the vec itself will use `Result<Option<T>, _>`. I don't think this inconsistency is necessarily that bad, but I remember how it was one of the reasons I went the other way.
