### ISSUE TITLE
Control Host Budget

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-sdk#382]
### What problem does your feature solve?

The [soroban-env-host](https://github.com/stellar/rs-soroban-env/tree/main/soroban-env-host) has budget machinery, but it can't be controlled from the SDK. This makes https://github.com/stellar/soroban-examples/issues/29 fail because the memory limit is exceeded.

### What would you like to see?

Make it possible to control the machinery so the limits can be set sufficiently high to write tests.

### What alternatives are there?

Make it possible to disable budgets in test. Change tests to use less memory (I suspect something unfortunate is happening here because we aren't using linear memory yet, related to https://github.com/stellar/rs-soroban-sdk/issues/247).

**Comment by leighmcculloch** [comment]
It sounds like something is going on here that we don't fully understand. Are you able to dig into why the budget is being exceeded? I don't think we want to disabled budgets entirely, since tests should help developers write efficient contracts.

**Comment by jonjove** [comment]
I'm already investigating why the budget is being exceeded, but I have some comments in response to yours:

I'm not sure the role of these tests is to help developers write efficient contracts. This is the case where I'm running a contract in native-mode, but it's calling a contract in wasm-mode. To determine if my contract is efficient, it would need to be running in wasm-mode which is not the case here.

I'm also not sure that saying we want the budgets to be low in tests make sense. For example, the entire test case in the liquidity pool contract runs with a single `Env` meaning that many contract calls are getting coupled without reseting budgets. That's why the main suggest was the ability to control the budget rather than disable it, so it could be appropriately reset.

Another option would be to actually use the `invoke_xdr` interface with a separate `Env` for every top-level call. I've considered this idea before, and it would create the most realistic testing experience.

**Comment by jayz22** [comment]
Can you add this line to your code? 
`host.get_budget_mut(|budget| budget.reset_unlimited());`
This will set the budget to unlimited (`u64::MAX`).

**Comment by leighmcculloch** [comment]
Another cause may be if you are using iterators anywhere. At the moment all iterators use slices which generate a new host object for every iteration. There are issues to address this in September when we have better profiling capabilities, but we might need to move these up:
- https://github.com/stellar/rs-soroban-sdk/issues/189
- https://github.com/stellar/rs-soroban-sdk/issues/191

**Comment by jayz22** [comment]
Currently the host budget parameters have not been calibrated and the [default limits](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/budget.rs#L259-L260) might be off. 
I opened this issue https://github.com/stellar/rs-soroban-env/issues/296 to track it.

**Comment by jonjove** [comment]
@jayz22 as far as I can tell, the SDK doesn't currently expose access to the budget machinery. Adding that support is what this issue is about.

**Comment by leighmcculloch** [comment]
If the default limits are not meaningful, and the budget machinery is in flux, simply disabling by default not just in tests but in general might be most appropriate so that tests and the CLI are not affected by unready logic. @jayz22 @graydon ?

**Comment by jayz22** [comment]
Yeah I think that makes sense. Per the code comment the 400_000 instruction limit (very roughly) runs about 100us. 
I've made the [PR](https://github.com/stellar/rs-soroban-env/pull/297) to temporarily set to unlimited if everyone else is ok with it.

**Comment by jonjove** [comment]
That's fine with me. We know it's not the long-term solution, but it will unblock progress.

**Comment by jonjove** [comment]
@leighmcculloch it's a bit hard to be sure, but as far as I can tell the limit I'm hitting is actually the `HostEventDebug` limit. But it's getting translated as memory limit, because the code is still experimental. I haven't yet figured out why I'm hitting the `HostEventDebug` limit, but at least that makes it clear this is probably not actually about memory.

**Comment by leighmcculloch** [comment]
Looks like we're able to do this now.
