### ISSUE TITLE
Add explicit compile error when contract fn name longer than 10 characters

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#384]

**Comment by fdesjardins** [comment]
I just ran into this while playing with some new examples in the `soroban-examples` repo:

```
error: custom attribute panicked
  --> my_single_offer/src/lib.rs:33:1
   |
33 | #[contractimpl(export_if = "export")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: called `Result::unwrap()` on an `Err` value: LengthExceedsMax
```

Granted, I'm a rust newbie, but I spent a good 20 minutes trying to figure this out before I realized it was the contract fn name. :smile: 

This seems like a strange limitation... is there a plan to allow for longer fn names in the future?

**Comment by leighmcculloch** [comment]
We definitely need a better error message. I wrote the code that generates this error and I too lost a good 20 minutes one time when my function was non-obviously too long. 

The 10 character limit exists because contract function names are reduced to 64bit integers which we can fit 10 characters into. They use the `Symbol` type. By using this format cross contract calls are smaller and more efficient. That plays a small part in reducing contract gas costs.

There are alternatives to this we could consider if the 10 character names are too inconvenient. 

We could create a second version of Symbol that has a smaller alphabet, say only lower case characters, so that we can fit more in.

Or, we could do something like Ethereum where function signatures are hashed and the first 4 bytes of the hash are used as the function name when calling them, effectively making the function name length unbound. We trade some problems for different problems though. https://docs.soliditylang.org/en/v0.8.13/abi-spec.html#function-selector

**Comment by fdesjardins** [comment]
Yeah, I discovered the Symbol type when I tried `cargo expand` after I shortened the fn name and the issue made more sense to me at that point.

The Ethereum strategy was actually my first thought on how to resolve this. Use some sort of hashing or shortening strategy, but then I wondered if that would make debugging or logging more difficult somehow (haven't gotten that deep into it yet). If so, maybe you could do a reversible shortening or have some sort of lookup?

Anyway, thanks for the response. Maybe it's a non-issue in the long run,  I'm still just experimenting. 😄

**Comment by leighmcculloch** [comment]
>I wondered if that would make debugging or logging more difficult

This is what I also expect is the tradeoff. 

For example, assume I want to write a contract with a function that is `pay_to_destination`.

Using the existing Symbol pattern, we'd might shorten the function name to `paytodest`:
```rust
impl Contract {
    pub fn paytodest(...) -> ... { ... }
}
```

And the function in the WASM file would look like:
```
- paytodest
```

Using a hash pattern, we could use our longer function name:
```rust
impl Contract {
    pub fn pay_to_destination(...) -> ... { ... }
}
```

The function in the WASM file would be something like:
```
- 35072c1a
```

We could aim of course for the developer rarely ever seeing the hashed value, but any abstraction we introduce will be leaky. The hashed function name will show up in Stellar transactions.

We could introduce a way to explicitly provide a shorter name to the function with an attribute like `#[contractfn(name = "paytodest")], but I think that adds additional complexity with little value.

I'm leaning towards sticking with the 10 character limit we have, and improving the error message so that the error message states explicitly what the limit is, and the name of the function, and that it shows the error on the function name too.

cc @graydon @jonjove if you have any thoughts.

**Comment by jonjove** [comment]
I'm good with the 10 character limit.

**Comment by leighmcculloch** [comment]
Given the significant pain point this issue is, I've changed the issue from `💎 Polish` to `🏆 Completion`.
