### ISSUE TITLE
Rename Binary to Bytes

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#385]
I think we should consider renaming the `Binary` type to `Bytes`.

In Solidity, their binary type uses the terms byte. https://docs.soliditylang.org/en/v0.8.11/types.html#fixed-size-byte-arrays

In Vyper, the new Ethereum lang, their binary type is named Bytes. https://vyper-by-example.org/values/

The term is immediately recognizable and less ambiguous as Binary. Binary can be ambiguous because people more often use the term to refer to executable binaries than they do byte slices. The term byte almost always shows up in any description I've casually given to what a Binary is.

Thoughts @jonjove @sisuresh @paulbellamy @tomerweller ?

**Comment by jonjove** [comment]
I'm not picky about this. Either is fine by me. It looks like `Bytes` is supported by the majority, so let's go for that.
