### ISSUE TITLE
Clean up Cargo.toml files for tests

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-sdk#428]
### What problem does your feature solve?

There are many inconsistencies and unnecessary lines in the Cargo.toml files for tests, such as https://github.com/stellar/rs-soroban-sdk/pull/426#discussion_r943588988.

### What would you like to see?

Make them uniform and bring them in line with our current development guidelines.

### What alternatives are there?

N/A

**Comment by jonjove** [comment]
Some of them depend on proptest (eg. add_i32) and some don't (eg. add_i64), but as far as I can tell none of them are actually using it. contract_data, linear_memory, vec don't specify `publish = false` but other tests do.

**Comment by leighmcculloch** [comment]
Thanks, adding this to the August iteration because the publish = false are likely to cause issues with releasing at the end of the iteration.

**Comment by leighmcculloch** [comment]
I removed prop_test recently from the sdk repo, and the publish thing got fixed I think at some point.
