### ISSUE TITLE
Add `Env` functions for publishing events via host functions

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#451]

**Comment by jayz22** [comment]
@leighmcculloch Looks like there is one small issue: 
The `sdk::Vec<T>` implies that vector must contain the same type. However, the [topics](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0056.md#topics) in `contract_event` is a vector of no such restriction. Do we need to loosen/expand the `sdk::Vec` to include heterogeneous types?

**Comment by leighmcculloch** [comment]
I don't think there is an elegant way to allow `sdk::Vec` to be both, and I don't think we should give up one for this.

Can we use a tuple instead? You  can use a macro to define the function five times for different topic values in the form:
- ()
- (a,)
- (a,b)
- (a,b,c)
- (a,b,c,d)
