### ISSUE TITLE
Move standard authorization into SDK

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-sdk#470]
### What problem does your feature solve?

Right now authorization lives in a random crate inside of soroban-examples, which is not obvious or intuitive. This has been practical while we've been improving it, but won't be practical once people actually need to use it.

### What would you like to see?

Standard authorization machinery should live in the SDK.

### What alternatives are there?

It would also be reasonable to put this machinery in a separate crate, which I imagine could have advantages since authorization also has a "not inside the host" part (generating messages and signatures externally) that could be used by the CLI.

**Comment by sisuresh** [comment]
Resolved by https://github.com/stellar/rs-soroban-sdk/pull/473
