### ISSUE TITLE
Add authorization unit tests

### ISSUE THREAD

**Issue by sisuresh** [stellar/rs-soroban-sdk#474]
Once the authorization crate has been finalized, we should add unit tests here - https://github.com/stellar/rs-soroban-sdk/blob/main/soroban-sdk-auth/tests/test.rs.

**Comment by dmkozh** [comment]
Reopening this in order to track adding more comprehensive coverage:
- Negative scenarios should be tested
- Different account types should be tested (specifically classic accounts)
- Some fuzzing is desirable too
