### ISSUE TITLE
Clean up on `events`

### ISSUE THREAD

**Issue by jayz22** [stellar/rs-soroban-sdk#480]
https://github.com/stellar/rs-soroban-sdk/pull/469#issuecomment-1225076389
1. Make `Vec` and acceptable input as a Topics. 
2. Move the `impl IntoVal` for tuples in a new file.

**Comment by sisuresh** [comment]
@jayz22 should this issue still be open?

**Comment by jayz22** [comment]
Yes I think these two TODO points are still outstanding.

**Comment by jayz22** [comment]
This is just a minor clean up, low priority. Moving to post testnet.
