### ISSUE TITLE
Update MessageV0 so fields are listed in alphabetical order

### ISSUE THREAD

**Issue by sisuresh** [stellar/rs-soroban-sdk#481]
The fields in a Soroban `contracttype` struct are in alphabetical order, not positional order. This change would make the struct match up with how the fields appear in the underlying Map.

Follow up: Should this ordering be enforced by the `contracttype` macro?

**Comment by leighmcculloch** [comment]
This ordering is a result of the `Map`/`ScMap` collection type being ordered and isn't actually controlled by `contracttype`. I don't think we nee to impose the order of the map onto the struct definition. What problems do you see by them being in different order?

**Comment by sisuresh** [comment]
The concern here is that a different order might confuse users and lead to questions.

**Comment by leighmcculloch** [comment]
This concern is valid to all UDTs, not just auth, so I think we should only address it in that broader context and not just for auth. It seems like there's three options

1. Do nothing.

2. Required UDTs fields to be ordered and raise a compiler error if not.

3. Make maps in the env preserve insertion order when serialized.

I suggest we do (1) for now, and explore the other options for the next release while measuring for feedback on if this is an issue tripping people up.
