### ISSUE TITLE
bigint! macro for conveniently creating bigints from u256 style strings

### ISSUE THREAD

**Issue by heytdep** [stellar/rs-soroban-sdk#493]
### What problem does your feature solve?
Operations involving large integers are pretty frequent in cryptography, it might be good to add u256 support for parsing large numbers into `BigInt`. 

### What would you like to see?
Possibly a `BigInt::from_u256()` method, or a `BigInt::parse`.

**Comment by jonjove** [comment]
@jayz22 originally added host functions to construct a `BigInt` from a big endian array. We didn't have a use for it at the time, but it seems like this is a good use case. Here's how I think this could all fit together

1. re-add those host functions
2. add a macro to the SDK like `bigint!("...digits...")` that converts the digits to the appropriate array at compile time and then calls the host function

One way the host functions could be designed would be to go from `Bytes` to `BigInt`. Then we can use linear memory to construct the `Bytes` where possible, making everything relatively efficient when hard-coded constants are available but also still usable when values are dynamic.

Does the developer-facing interface `bigint!` sound reasonable to you @heytdep?

**Comment by jonjove** [comment]
I realized I missed a detail. We would also need to expose a `BigInt::from_bytes` function (or equivalent using traits) that can be used in the dynamic case, and that can be used behind the scenes by `bigint!`.

**Comment by heytdep** [comment]
a macro for that seems just what's needed, so to make sure I understand clearly:
1. the `bigint!` macro converts the number into an array
2. the host will know that the array corresponds to a number and will construct a BigInt from that?

Also, say the `let big_num = bigint!("0x0999e3730d9a8120caea0a065b8ce05577ba27f61ca315f06e212b647a9c93e8")` would have the `BigInt` type or the type of a slice/vector?

**Comment by jonjove** [comment]
That's basically right, except the macro would explicitly tell the host that it's a `BigInt`. The intention is that `let big_num = bigint!("0x0999e3730d9a8120caea0a065b8ce05577ba27f61ca315f06e212b647a9c93e8")` would have type `BigInt`. Trying to get a bit more specific, the `bigint!` macro would work something like the following

1. convert the digits to a `[u8]`
2. use `Bytes::from_array` on the `[u8]` to construct a `Bytes`
3. use `BigInt::from_bytes` on the `Bytes` to construct a `BigInt`

if that makes sense?

**Comment by jayz22** [comment]
I'll work on adding them back to the host (maybe sdk too), should be straightforward.

**Comment by leighmcculloch** [comment]
> Also, say the let big_num = bigint!("0x0999e3730d9a8120caea0a065b8ce05577ba27f61ca315f06e212b647a9c93e8") would have the BigInt type or the type of a slice/vector?

We have a `bytes!` macro that accepts a byte array and creates a Bytes, but it might be convenient to have a hex version of this as I think you're hinting at. I created https://github.com/stellar/rs-soroban-sdk/issues/499 for that separate issue.

**Comment by leighmcculloch** [comment]
Implemented in https://github.com/stellar/rs-soroban-sdk/pull/501.

Example usage:
```rust
let env = Env::default();

let big = bigint!(&env, 0xfded3f55dec47250a52a8c0bb7038e72fa6ffaae33562f77cd2b629ef7fd424d);
assert_eq!(big.bits(), 256);

let big = bigint!(&env, -5);
assert_eq!(big.to_i64(), -5i64);
```
