### ISSUE TITLE
Support UDT enums with non-unit tuple variants

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-sdk#494]
### What problem does your feature solve?

Right now it's not permitted to do

```rust
#[contracttype]
enum Enum {
    Variant(u32, u32),
}
```

Related to https://github.com/stellar/rs-soroban-sdk/issues/427

### What would you like to see?

Allow UDT enums with non-unit tuple variants.

### What alternatives are there?

TODO

**Comment by graydon** [comment]
Fixed in https://github.com/stellar/rs-soroban-sdk/pull/850
