### ISSUE TITLE
Register External Contract for Unit Testing

### ISSUE THREAD

**Issue by mootz12** [stellar/rs-soroban-sdk#518]
### What version are you using?
Commit `b4cc8fc`

### What did you do?

Import an external contract and register it using the following function:
```
soroban_sdk::env::Env
pub fn register_contract<T>(&self, contract_id: &BytesN<32>, contract: T)
```
in an "integration" test format (within the `tests` folder). The function will not compile with the following error:
```
the trait `ContractFunctionSet` is not implemented for `ExampleContract`
```

The test works as expected in the "unit" test format.

Minimum example repository here: https://github.com/mootz12/soroban-external-contract-test

### What did you expect to see?

Imported external contracts can be registered against the env without having to rely on test structs (as seen with consumption of the token contract https://github.com/stellar/soroban-token-contract/blob/main/src/testutils.rs)

### What did you see instead?

Testing can still be completed using the "unit" test approach or with a test struct.

**Comment by leighmcculloch** [comment]
This is because the test utilities are only compiled in for test builds where the test cfg is enabled, or when testutils feature is enabled. Unit tests are built with the test cfg enabled. Integration tests in Rust do not. Integration tests build the crate without the test cfg.

I would recommend building integration tests that use the test utilities with a `#![cfg(feature = "testutils")]` at the top of the integration test and then enabling the testutils feature when running tests.

**Comment by jonjove** [comment]
@leighmcculloch when I was trying to reproduce the issue reported by @mootz12 I did exactly what you suggested, and I started getting some other errors about missing conversions (coming from `contractimpl`)
```rust
error[E0277]: the trait bound `ScVec: TryFrom<(&soroban_sdk::BytesN<32_usize>, &str, &u64)>` is not satisfied
  --> src/lib.rs:15:1
   |
15 | #[contractimpl]
   | ^^^^^^^^^^^^^^^ the trait `TryFrom<(&soroban_sdk::BytesN<32_usize>, &str, &u64)>` is not implemented for `ScVec`
   |
   = help: the following other types implement trait `TryFrom<T>`:
             <ScVec as TryFrom<&std::vec::Vec<ScVal>>>
             <ScVec as TryFrom<(T0, T1)>>
             <ScVec as TryFrom<(T0, T1, T2)>>
             <ScVec as TryFrom<(T0, T1, T2, T3)>>
             <ScVec as TryFrom<(T0, T1, T2, T3, T4)>>
             <ScVec as TryFrom<(T0, T1, T2, T3, T4, T5)>>
             <ScVec as TryFrom<(T0, T1, T2, T3, T4, T5, T6)>>
             <ScVec as TryFrom<(T0, T1, T2, T3, T4, T5, T6, T7)>>
           and 6 others
   = note: required because of the requirements on the impl of `TryInto<ScVec>` for `(&soroban_sdk::BytesN<32_usize>, &str, &u64)`
   = note: this error originates in the attribute macro `contractimpl` (in Nightly builds, run with -Z macro-backtrace for more info)
```
That error is originating from [derive_client](https://github.com/stellar/rs-soroban-sdk/blob/0a4dbfc2fd16289a488597e96556d86989abbed2/soroban-sdk-macros/src/derive_client.rs#L131) and [derive_fn](https://github.com/stellar/rs-soroban-sdk/blob/0a4dbfc2fd16289a488597e96556d86989abbed2/soroban-sdk-macros/src/derive_fn.rs#L267). This error doesn't occur when setting up the code in "unit test" style, so there is probably some other feature issue going on.

**Comment by mootz12** [comment]
@jonjove I also have the same issue, although my note claims it originates in the macro `::soroban_sdk::contractclient`

Did a bit more poking around, and noticed that the example contract listed does not build with `cargo build --features testutils` (due to the error Jon documented). It appears to be caused by having a function argument of `u64`, since I can resolve the error with the following code update:

```
    // update trait and tests to match...

    fn do_thing(x: u32) -> u64 {
        u64::from(x + 1)
    }
```

At this point, unit testing and integration testing both work. (although, testing in Integration mode might warrant some additional documentation around the use of `testutils` features)

**Comment by jonjove** [comment]
@mootz12 that was exactly the piece of information I needed to find what conversion was missing, thank you! See https://github.com/stellar/rs-stellar-xdr/pull/149. Can you try picking that change up and see if it fixes your issue?

**Comment by mootz12** [comment]
Yup, confirmed that both of these work as expected after getting your change:
```
cargo test --features testutils
```
and
```
cargo build --features testutils
```

**Comment by leighmcculloch** [comment]
I added docs about integration tests on two pages in https://github.com/stellar/soroban-docs/pull/88 and https://github.com/stellar/soroban-docs/pull/91. See those issues for screenshots.
