### ISSUE TITLE
Re-evaluate register_test_contract / register_wasm_contract

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-sdk#530]
### What problem does your feature solve?

These functions are now bespoke relative to the broader `deployer` mechanism recently added.

### What would you like to see?

We might be able to unify this with the `deployer` mechanism.

### What alternatives are there?

N/A

**Comment by leighmcculloch** [comment]
While working on examples and docs updates it occurred to me that using the deployer will actually make the code more ergonomic. Although it also highlighted to me that we might still need some bespokeness.

For example, this is littered throughout our tests:
```rust
let env = Env::default();
let contract_id = BytesN::from_array(&env, &[0; 32]);
env.register_contract(&contract_id, Contract);
```

But with a change to deployer we could have:
```rust
let env = Env::default();
let contract_id = env.deployer().from_test().deploy(Contract);
```

The side-effect improvements are:
- Teaching the developer where real deploys happen.
- No need to create fixed contract IDs, which is not intuitive.

**Comment by leighmcculloch** [comment]
This is likely to get overhauled soon because @dmkozh is currently reworking deployment with the env crates.
