### ISSUE TITLE
Auth usability and alternative design considerations

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#558]

**Comment by sisuresh** [comment]
@leighmcculloch Is this just a running issue we'll leave open and roll into future iterations until we finalize auth?

**Comment by leighmcculloch** [comment]
Yup. We've both been doing some dogfooding. There isn't really a specific thing to do other than dogfooding and identifying things to improve, and if lightweight enough fix them as part of this. I want to do some more with the latest changes, but we might be good now. I'll update the issue title to match and assign it to both of us.
