### ISSUE TITLE
Discussion: Make the domain/context generic in auth

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#577]
The domain/context of a signature in the auth SDK is currently fixed to being a few fixed values:
- network passphrase
- contract ID
- function invoked

It's come up in conversations in a few places that the domain/context of a signature may need to be flexible. For example:
- https://github.com/stellar/rs-soroban-sdk/pull/574#issuecomment-1241238208
- https://github.com/stellar/rs-soroban-sdk/issues/477#issuecomment-1225872696

It's also clear that contracts do need flexible domains, for example:
- https://github.com/stellar/starbridge/pull/93

On the one hand providing domain flexibility could be a footgun because a developer could forget to use it, or use it insufficiently.

On the other hand providing domain rigidity could be a footgun because a developer could think the problem requires none of their attention, when in fact their situation requires a more comprehensive or more specific domain.

Unfortunately we always need the developer to understand how authentication works as they are the only person who knows for their contract what authentication is required. We do need to make sure a domain is used, and make it really easy to choose a good domain though.

If we make the domain simply an `impl IntoVal<Env, RawVal>` we allow a developer to use any domain they need. We can then also provide default domains to use. For example we could provide several domains for developers to choose from:
- `soroban_auth::single_invocation_domain`
   - network passphrase
   - contract ID
   - function invoked
- `soroban_auth::full_call_stack_domain`
   - network passphrase
   - full contract call stack in the form `Vec<(BytesN<32>, Symbol)>`

cc @sisuresh @jonjove

**Comment by sisuresh** [comment]
It would be ideal if we could keep the simple auth case the way it is now, and expose a second method that gives the user more control over how they want auth to work (custom domain, multiple signatures, etc...)

The "simple case" still needs to be defined though. If we could somehow combine `single_invocation_domain` and `full_call_stack_domain`, that would simplify the options, and contract writers wouldn't get stuck in a situation where users can't use the contract in the context that they want. The auth flow could always check the call stack, but exclude the most recent call stack frame, so users would sign an empty call stack in the simple case? The current contract id and function are already on SignaturePayload, so they don't need to be included in the call stack. But this presents some other challenges that we've discussed [here](https://github.com/stellar/rs-soroban-sdk/pull/574#issuecomment-1241192968).

**Comment by leighmcculloch** [comment]
The call stack option would work for both cases if there was a way to say that partial match or full stack match was required.

**Comment by leighmcculloch** [comment]
@tamirms suggested we look at https://eips.ethereum.org/EIPS/eip-712, which defines a standard for signing structured data on Ethereum. It also happens to define a standard for specifying a domain, the `struct EIP712Domain` in the standard, based around five components, that isn't too different to what we have today.

**Comment by jonjove** [comment]
@leighmcculloch most of the initial auth work is based off of my observations from EIP-712 and EIP-2612 (which is built on 712), so I am very in line with drawing inspiration from that.

The main advantage of having a standard domain is that it makes other tooling like wallets and the CLI much simpler. Most of the work we've done in the past weeks has been around making it easy for tooling to work with signatures. This would be a big departure from that, and I think any step in this direction would need to address how one would be able to construct the correct signature.

**Comment by tamirms** [comment]
I'm confused why it's necessary to include the contracts stack trace in the payload to be signed. I think that will make it to sign the payload off-chain, especially for SDKs not written in rust. 

> the nonce is absent and it is up to the application to prevent replay, which I like and I think it would simplify our auth interface to consider this.

I also agree with @leighmcculloch's suggestion of removing the nonce

I think it would be useful to have a function which generates the following binary payload:

```
    let msg = SignaturePayloadV0 {
        function,
        contract: env.get_current_contract(),
        network: env.ledger().network_passphrase(),
        args,
    };
    let msg_bin = SignaturePayload::V0(msg).serialize(env);
```
Having such a function would be useful for smart contracts that want to store payloads which it has accepted in a set in order to prevent replay attacks.

**Comment by jonjove** [comment]
> I'm confused why it's necessary to include the contracts stack trace in the payload to be signed. I think that will make it to sign the payload off-chain, especially for SDKs not written in rust.
@tamirms take a look at https://github.com/stellar/stellar-protocol/issues/1289. It's not strictly necessary, one can do simple things without this. Doing complex things, however, is unsafe.

**Comment by tamirms** [comment]
having read through https://github.com/stellar/stellar-protocol/issues/1289 , I don't think the stack trace solution will be widely used by smart contract developers. If you're trying to optimize for low transaction fees it seems better to avoid operations like hashing a call stack

**Comment by jonjove** [comment]
It's not about low transaction fees. It's about capabilities that can't easily be expressed otherwise.

But I acknowledge that people might not be interested in these capabilities. It's something that @sisuresh and I have discussed a lot.

**Comment by leighmcculloch** [comment]
I've opened a separate issue for removing nonce validation from soroban-auth, since it is somewhat separate to this conversation: https://github.com/stellar/rs-soroban-sdk/issues/590.

**Comment by sisuresh** [comment]
@leighmcculloch 
> the domain is very simple and doesn't include a contracts full call stack. Is there anywhere in these sta dards that a full stack shows up?

EIP-712 has a section on `Frontrunning attacks`. Our call stack solution attempts to mitigate this attack, while the EIP just makes the user aware of the potential issue. I haven't found anything else yet that uses the call stack.

> the domain includes the verifying contract ID. Afaict this isn't necessarily the receiving contract? Is this accurate?

What do you mean by "receiving contract"? The first contract that the signature is submitted to? I think that would be the "forwarding contract". I interpret "receiving contract" as the contract that does the verification. The `contract` field in our `SignaturePayloadV0` works the same way as EIP-712. It's the contract that does the verification.

**Comment by leighmcculloch** [comment]
I think we should close this issue because of:

>The main advantage of having a standard domain is that it makes other tooling like wallets and the CLI much simpler.

And keep the domain as it is, which is very simple and similar to EIP-712:
https://github.com/stellar/rs-soroban-sdk/blob/6d61c900d88fd43cd24487a1491f5661e12e445b/soroban-auth/src/public_types.rs#L45-L48

@jonjove @sisuresh @tamirms

**Comment by leighmcculloch** [comment]
Sounds like from https://github.com/stellar/stellar-protocol/issues/1289#issuecomment-1246999467 that something like this issue is still required.

**Comment by leighmcculloch** [comment]
I think that sounds good 👍🏻.

**Comment by leighmcculloch** [comment]
How about we make the salt an `Optional<RawVal>`? Then it can be anything, such as a Vec containing a contract call stack.

**Comment by jonjove** [comment]
I'm good with that, but it comes back to the question of how should a wallet produce signatures?

**Comment by sisuresh** [comment]
This is a question that needs to be answered regardless of the domain right? We have the same problem when it comes to the `args` (I'm not trying to brush off this problem. Just want to make sure I understand the issue).

**Comment by leighmcculloch** [comment]
The story for how signatures get produced for the case where `salt: None` is relatively simple, since the contract id, function, and args are all much easier to define for a single invocation. For the case where the `salt: Some(_)` we're heading into very custom territory. Do you think we need to define it well or will Dapps just provide the salt XDR encoded of the ScVal?
