### ISSUE TITLE
Generate debug events on conversion errors

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#617]
Follow up to #482

**Comment by graydon** [comment]
@leighmcculloch Are we strictly talking about inside of `TryFromVal` impls, or more generally (eg. inside `TryFrom`?) The latter is going to be .. hard.

**Comment by graydon** [comment]
I noticed while working on the value overhaul a fair amount of inconsistency in which conversion paths in common, env, guest and SDK do or don't generate debug events. I'm not sure it's a high priority to address (these are debug events so we can add/remove them over time, I think! -- depending on whether we allow non-metered debug events) but it would probably be good to make this more systematic.

**Comment by graydon** [comment]
I think as much of this as can be done is done in https://github.com/stellar/rs-soroban-env/pull/806 and the remainder are contexts where we don't have an Env so can't generate anything more.
