### ISSUE TITLE
Add support for contracttype on type aliases

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#623]
I'm changing contracttype so that it has an export attribute, which will be true by default, except for contracttypes that are imported. Contract types that are imported will not be exported by default because it is the least surprise behavior and ensures that importing a contract with types that have the same name as types already in the contract do not collide in the contract spec (which is an issue we have now).

**Comment by jonjove** [comment]
This is great. I was just thinking about the fact that the token example exports `AllowanceDataKey` and `DataKey` into the contract spec even though those are part of the private interface. They really shouldn't appear in the contract spec and (assuming I understand correctly what you are going to do) it should now be possible to remove them from it.

**Comment by leighmcculloch** [comment]
@jonjove I've change the `contractimport!` macro as a part of the work for https://github.com/stellar/rs-soroban-sdk/issues/622 so that it no longer automatically exports types from an imported contract.

The intent with this issue was to provide a mechanism through which someone could choose to reexport a type from another contract. I had two ideas in mind:

- (This issue.) Use type aliases as a convenient syntax for reexporting. Because the spec XDR is a const function on each type, it is relatively easy to generate a const function for the alias that just calls the same function on the original type. The hope was to add a prefix spec entry on to the front of the original spec entry, where the prefix spec entry provided an alias for the latter.

- Add to the `contractimport!` macro an attribute where you can list off the names of types you'd like reexported.

I started work on (1) and it was looking good, but in the process it occurred to me that this might not be a good practice for us to encourage. Reexporting another contracts types is essentially defining the form of user input without having that form well specified clearly in your code. Given that user input is not trusted, a contract should maybe not trust user input it can't see clearly, which is the case with generated code.

It also occurred to me that this isn't a critical issue. Even though it is inconvenient, someone can use the `soroban-cli gen --output rust --wasm <file>` command to generate code for another contract's type, and then copy and paste it into their code, and after copy pasting it they can remove the `export = false` attribute that is on the type.

There's enough ambiguity as to whether this is a good practice I'm going to close this issue and we can reopen it if someone expresses that it is a real and dire need.
