### ISSUE TITLE
Add a clear error message for when an integer enum doesn't have derive(Copy)

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#630]
Integer enums to be used as contracttype's need to have `derive(Copy)`. This is so that we can convert a reference to an integer enum into a u32.

Right now the error message displayed is ambiguous because it is an error generated from generated code that uses the type in a way that requires a Copy.

We should try and detect from the other attributes on the type whether the type has Copy derived. If it hasn't, we should display a focused error message.

This is a follow up to https://github.com/stellar/rs-soroban-sdk/issues/217

**Comment by jayz22** [comment]
Assigning myself to take a look at this one.

**Comment by jayz22** [comment]
The change has been reverted in https://github.com/stellar/rs-soroban-sdk/pull/1283 due to uncovered corner cases. Reopening this issue.

**Comment by leighmcculloch** [comment]
I don't think we can overcome the uncovered corner cases unfortunately, as there's no way to catch a derive(Copy) if it is placed above the attribute, which was a limitation of the attributes I wasn't aware of at the time.

Another solution is we stop assuming that the enums should be copy in other macro generated code, then this becomes a non-issue for a slight probable loss of performance in some cases. This might not be realistic though.

**Comment by leighmcculloch** [comment]
@jayz22 I've opened the following change that removes the need for an error message by making it so that errors no longer need to derive Copy:
- https://github.com/stellar/rs-soroban-sdk/pull/1292

**Comment by leighmcculloch** [comment]
Another option from the friendly folks in Rust discord is to insert this into the generated code:
```rust
const _: () = { fn assert_copy(v: #enum_ident) -> impl Copy { v } };
```
That results then in this very direct error:
```
error[E0277]: the trait bound `Error: core::marker::Copy` is not satisfied
 --> tests/errors/src/lib.rs:9:1
  |
9 | #[contracterror]
  | ^^^^^^^^^^^^^^^^ the trait `core::marker::Copy` is not implemented for `Error`
  |
help: consider annotating `Error` with `#[derive(Copy)]`
  |
11+ #[derive(Copy)]
12| pub enum Error {
  |

```

**Comment by leighmcculloch** [comment]
@jayz22 I've opened a new change that uses the approach above to generate a nicer error message. Since this works I think it is preferred because it allows us to do conversions from the enum types to their integer types in the generated code without having to implement match tables between the values and integer constants.
- https://github.com/stellar/rs-soroban-sdk/issues/630
