### ISSUE TITLE
#[contracttype] tuple structs support

### ISSUE THREAD

**Issue by heytdep** [stellar/rs-soroban-sdk#663]
### What problem does your feature solve?
It seems that structures without named fields aren't supported for the `contracttype` proc macro.

### What would you like to see?
Currently, by writing a struct such as the following:

```rust
#[contracttype]
pub struct TimeStamp(BigInt);
```

There are complaints about the fact that the structure does not have fields:
![storage_rs](https://user-images.githubusercontent.com/70587974/191921989-c619dae9-159f-43ca-b346-81c71f3261e3.png)

This shouldn't happen since it's a common practice in rust to use tuple structs to create new types.

**Comment by leighmcculloch** [comment]
I initially thought this just hadn't been implemented, but actually looking at the code there is code specifically to make the tuple case work, but it appears we were missing a test case and it's a bug. Fixing in #665.

Note that in your example the `0` field of the struct is a non-public field, and only public fields are supported by `contracttype` at the moment. I've opened a separate issue to track addressing non-pub fields as a possibility:
- https://github.com/stellar/rs-soroban-sdk/issues/666

**Comment by leighmcculloch** [comment]
Also as a follow up to this we should check if tuple structs can be code generated successfully too:
- https://github.com/stellar/rs-soroban-sdk/issues/667
