### ISSUE TITLE
Consider consolidating Account and Contract into an Address in soroban_auth::Identifier

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#708]
As a follow up to #707 we should consider conlidating the Account and Contract variants of `soroban_auth::Identifier` into a single `Address` variant that contains a `Address`. It would make the type a little more opaque at the surface, although it will also increase the cost of using the type.

There is nothing urgent about this thought, and this issue is something for us to consider for a future iteration.

**Comment by sisuresh** [comment]
This should be resolved once soroban-auth is removed and auth-next takes its place. (cc. @dmkozh)

**Comment by dmkozh** [comment]
Closing this now in favor of Auth Next related issues.
