### ISSUE TITLE
Offer built-in contracts via contractimport

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#727]
To import a built-in contract developers must download the `soroban_token_spec.wasm` file and reference it in their code base.

However, we could provide a macro that does the same for them using the `sorobab_token_spec` crate. 

We could make it a new macro like:
```rust
contractimportbuiltin!(token)
```

Or we could add it as an option to the existing macro:
```rust
contractimport!(builtin = "token")
```

I'm leaning towards the latter because it doesn't increase the macro surface area. 

This wouldn't be a breaking change. People could still do it the existing way, because that's how non-builtin contracts are imported.

Reasons to do this:
- developers don't have to ensure they have the right version of the .wasm file alongside their own for something the SDK can tell them.
- one less thing that must be manually coordonated
- one less binary in everyone's repos
- relatively low effort

**Comment by leighmcculloch** [comment]
A problem with the above is that it would require a circular reference between the `soroban_sdk` and `soroban_token_spec`, assuming the spec continues to live in a separate crate.

To do the above would require moving the `soroban_token_spec` into the `soroban_sdk`, which would probably be okay.

Alternative, we could make two extra crates and build a new proc-macro for each builtin in new crates. This has some advantages that people are very explicitly importing this aspect of the SDK only if they needed it, so it leans into modularisation. The disadvantage is that people have to import extra crates for something that otherwise seems rather core to developing contracts on Soroban. The way I see it could work is:
- Add a new crate `soroban_token_macros` that contains the macro that uses `soroban_token_spec` to generate using `soroban_spec`.
- Add a new crate `soroban_token` that reexports the macro.
- Users call `soroban_token::contractimport!()`

**Comment by JakeUrban** [comment]
Hey Leigh, has there been any changes or updates not documented here related to this issue?

**Comment by leighmcculloch** [comment]
@JakeUrban There's nothing new in the SDK relating to this change. I attempted to spike an approach but ran into multiple technical blockers.

**Comment by leighmcculloch** [comment]
> where can this be downloaded from?

It is not hosted anywhere at this point.

**Comment by Shaptic** [comment]
Ah okay, maybe change to "developers must **build**," then? We could also build and add to a `dist/` folder with CI when GH tags a release, or something?

**Comment by sisuresh** [comment]
@leighmcculloch I'm planning on working on this soon. Do you have more info on your spike? Would be good to know what issues you ran into before I potentially run into the same.
