### ISSUE TITLE
Add support for getting contract IDs that would be assigned to deployments

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#730]
We need to add support for getting contract IDs that would be assigned to deployments. 

We have stub functions already in the code for this capability, but they aren't filled in because the host functions don't exist for them to work. For example:
https://github.com/stellar/rs-soroban-sdk/blob/5a6429c297e9a9135dc797029ddc7a79ca3abee6/soroban-sdk/src/deploy.rs#L113-L117

The reason to provide this functionality is two fold:
- So that in tests developers can pre-generate a contract ID that they expect will be used later in the test.
- So that contracts can store the contract ID of a contract given inputs.

Dependent on https://github.com/stellar/rs-soroban-env/issues/538
Blocking https://github.com/stellar/soroban-examples/issues/152

**Comment by anupsdf** [comment]
@leighmcculloch , Can this be closed now that we have [get_contract_id](https://github.com/stellar/rs-soroban-env/pull/853) host fn?

**Comment by leighmcculloch** [comment]
The host fn was implemented, but the sdk work to use it has not been completed, which is what this issue is for.

For example:

https://github.com/stellar/rs-soroban-sdk/blob/f743d6f9e49caa08924318907cd0588b60d7f187/soroban-sdk/src/deploy.rs#L152-L157

https://github.com/stellar/rs-soroban-sdk/blob/f743d6f9e49caa08924318907cd0588b60d7f187/soroban-sdk/src/deploy.rs#L184-L188

Also interesting note those two functions used to be named the same, and should still be named the same. Strange that one has been renamed without the other.

**Comment by leighmcculloch** [comment]
Closed by #1086
