### ISSUE TITLE
Experiment with methods to automatically include debug event logs in tests using the SDK

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#734]

**Comment by graydon** [comment]
@leighmcculloch what do you mean by "include"? Like some kind of test vector that saves the expected debug-event output and compares it on future runs? Or a mechanism to inject things into the log? Something else?

**Comment by leighmcculloch** [comment]
I was planning on experimenting with injecting `env.logs().print()` at the end of every test run via a macro, but I don't love that idea. We don't need more macros.

Could we add a feature to `soroban-env-host` to make it immediately print to stdout any debug logs as they occur. And the SDK can enable that feature when importing the crate.

Because the logs are immediately printed we could expand any host objects too so the logs are better.

Wdyt?
