### ISSUE TITLE
Embed Build and Version into contracts

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#735]
Months ago we talked about the possibility of embedding meta information, such as the version of SDK and Auth SDK into contracts. This issue is to debate that.

The main requirement that drove the initial intent of this was so that it would help us debug problems in contracts as we release new SDKS, new Envs, etc. We already get visibility into this to a degree with the env interface version that is embedded into built contracts in the 'env meta' entries.

So there's two time frames of uses:
- Before a pubnet release we are likely to have many futurenets which are incompatible with each other, and a fast evolving SDK that accompanies them. This seems very useful as we've generally found debugging what a contract has used or been built with as difficult.
- After pubnet it may be useful, but unclear how much.

Because of that second point if we implement this we should at a point close to pubnet launch consider removing this feature. It may have limited utility past that point.

This isn't urgent, but if we agree on implementing something like this, I'd like to get this into a near future release so we don't have too many contracts out there that we can't help people debug their version and state of why it isn't working.

cc @graydon

**Comment by leighmcculloch** [comment]
There's a sketch here of a rather generic set of entries we could use for this: https://github.com/stellar/stellar-xdr-next/pull/49

Note that this meta is not the same as the env-meta. The env-meta is known to be something we want to be long lasting, and it is part of the protocol with well defined fields that the Host will use. This meta is in the user defined / application land, and not intended to be used by the network in anyway.

**Comment by sisuresh** [comment]
The xdr [here](https://github.com/stellar/stellar-xdr/pull/82) can be used to store this information.

**Comment by anupsdf** [comment]
Discussed this with @leighmcculloch and this should be targeted for V1.
