### ISSUE TITLE
Test utilities for creating trust lines, assets, issuance, etc for accounts

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#736]
We still need to add test utilities for creating trust lines for accounts.

The main use case of these test utilities is to give people the ability to exercise import and export with tokens that are linked to assets.

**Comment by leighmcculloch** [comment]
```rust
env.accounts().set_trust_line(...)
```

```rust
env.deployer().with_source_account(...).deploy_token(...)
env.deployer().with_source_account(...).deploy_token_for_issued_asset(...)
env.deployer().with_source_account(...).deploy_token_for_native_asset(...)
```

**Comment by sisuresh** [comment]
More context in this duplicate issue - https://github.com/stellar/rs-soroban-sdk/issues/826.

**Comment by leighmcculloch** [comment]
Closing as we no longer have an immediate need for these in contract tests since contract tests use contract addresses for testing. Please reopen if we discover otherwise.
