### ISSUE TITLE
Auth account signature test utilities

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#741]
https://github.com/stellar/rs-soroban-sdk/blob/b66355c40288a245b91901c1bfa366793b656672/soroban-auth/src/testutils.rs#L75-L78

**Comment by leighmcculloch** [comment]
Related https://discord.com/channels/897514728459468821/966788672164855829/1034337516712624158

**Comment by heytdep** [comment]
@leighmcculloch I think I have implemented this one for my latest sorobanathon submission, linking it here in case it comes in handy https://github.com/Xycloo/soroban-build-signatures/blob/main/src/main.rs#L42

**Comment by sisuresh** [comment]
Closing because auth-next will make soroban-auth obsolete.
