### ISSUE TITLE
contractimport fails when imported contract defines a contracterror

### ISSUE THREAD

**Issue by mootz12** [stellar/rs-soroban-sdk#758]
### What version are you using?
```0.2.0```

### What did you do?
Importing contracts with the macro `contractimport` fails for contracts with an `Error` enum defined as shown in the examples.

See example branch (and pardon the bad naming... ~~with_event~~ -> with_error): https://github.com/mootz12/soroban-examples/tree/bug/import_contract_with_event/example_error_consumer

### What did you expect to see?
The contract to be successfully imported. 

### What did you see instead?
```
error[E0507]: cannot move out of `*val` which is behind a shared reference
 --> example_error_consumer/src/lib.rs:6:5
  |
6 | /     soroban_sdk::contractimport!(
7 | |         file = "../target/wasm32-unknown-unknown/release/soroban_errors_contract.wasm"
8 | |     );
  | |_____^ move occurs because `*val` has type `error_contract::Error`, which does not implement the `Copy` trait
  |
  = note: this error originates in the attribute macro `soroban_sdk::contracterror` (in Nightly builds, run with -Z macro-backtrace for more info)
```
Where the `Error` in question does implement Copy:
https://github.com/mootz12/soroban-examples/blob/bug/import_contract_with_event/errors/src/lib.rs#L4-L9

**Comment by leighmcculloch** [comment]
Thanks for identifying this issue @mootz12. I've published a fix in `v0.2.1`.
