### ISSUE TITLE
Add docs to contract spec

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#806]
We should consider adding docs to the contract specs generated by contracts.

Why: So contract developers can communicate in the spec about the interface they're exposing. So that those comments can show up in other developers IDEs when they import, and in other places like the CLI.

In practice this would mean taking the doc comments (`///` or `#[doc = "..."]`) on functions, fields, types, etc and including them in the contract spec XDR.

The contract specs would likely be outputted in several locations:
- In code generated by `contractimport!` in the sdk.
- In the `soroban inspect` command in the cli.
- In the `soroban gen` command in the cli.
- In the `soroban invoke` commands help pages in the cli.

The effort to do this naively is really simple, it just requires modifying the XDR to include some additional fields, and modifying the SDK macros.

Doc comments might be long and a CLI interface is compact, so we should expect some users of the docs to truncate the docs.

There is a security concern we should evaluate, and that is that doc comments are executable in Rust applications.

cc @willemneal

**Comment by willemneal** [comment]
According to Cargo:

    Doc tests for libraries may be disabled by setting doctest = false for the library in the manifest.

So this is one option. It's not we are using them anyway. However, it's still up to the user to ensure that it's there. So we could add a `test` command to the CLI which would ensure that no doc tests were run. It would also be useful to potentially start a sever before calling `cargo test` or even [nextest](https://nexte.st/).
