### ISSUE TITLE
Allow hashing of arbitrary data

### ISSUE THREAD

**Issue by hanseartic** [stellar/rs-soroban-sdk#809]
Currently there is `crypto().sha256(b: &Bytes)` which allows to generate a (sha256) hash over given `Bytes`. Unfortunately this is limited to `Bytes`.

### What problem does your feature solve?
This feature would allow to generate a hash over other data that is not necessarily only `Bytes`. One example would be to generate an ID out of user-provided input and use it as a storage key:
```rust
pub fn add_data(env: Env, data: CustomStruct) -> BytesN<32> {
  let data_store = env.storage().get_unchecked::<_, Map<BytesN<32>, CustomStruct>>(symbol!("data")).unwrap();
  
  // this currently is **not** possible as the original value is not `Bytes`
  let id = env.crypto().sha256(data.to_raw().into());
  data_store.set(id, data);
  env.storage().set(symbol!("data"), data_store);
  id
}
```

### What would you like to see?
I would like to have a way to hash more than just `Bytes`.

### What alternatives are there?
Currently none (as of discussion on [discord](https://discord.com/channels/897514728459468821/966788672164855829/1053346091258609745)).

**Comment by leighmcculloch** [comment]
You can do this today by serializing an object into Bytes and then hashing it. You should be able to do this with:

```rust
let bytes: Bytes = (10u64, true).serialize(&env);
let hash: BytesN<32> = env.crypto().sha256(&bytes);
```

All the types, including `Map` in your example, should be serializable into `Bytes`.

I'll close the issue because I think this addresses the ask. Please reopen if not.
