### ISSUE TITLE
Provide methods that publish standard token events

### ISSUE THREAD

**Issue by sisuresh** [stellar/rs-soroban-sdk#812]
We should provide methods in the sdk that help contracts emit the events expected from the token interface. This will make token events less error prone and easier to emit.

**Comment by leighmcculloch** [comment]
It sounds like this could live in a token sdk that contains other things that help with token development.

**Comment by sisuresh** [comment]
We should also add a standard `Trade` event. Discussion about this here - https://discord.com/channels/897514728459468821/1040360159593115751/1040360159593115751.
