### ISSUE TITLE
Change structs with field names encoding from map to vector 

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#816]
We should change structs with field names encoding so that they are encoded to vectors.

At moment they are encoded to maps where the field names are placed in symbols as the key.

However this is less effecient than a Vec, and people will want tow rite efficient contracts.

**Comment by leighmcculloch** [comment]
https://discord.com/channels/897514728459468821/1060582088216158338/1060615396069212270

**Comment by graydon** [comment]
I'll take this, it's probably worth doing at the same time as https://github.com/stellar/rs-soroban-env/issues/596

**Comment by leighmcculloch** [comment]
I realize I opened this issue, but after our more recent discussions, specifically relating to https://github.com/stellar/rs-soroban-env/issues/596, I think we might be jumping to soon to implement this.

I think if we implement bulk map host functions as part of https://github.com/stellar/rs-soroban-env/issues/596, we might get enough of a gain such that we can keep using maps for structs. The big gain for maps is that the resulting data will be self describing.

Even after we do that the difference is still a significant saving to change structs to vecs, it is a relatively small change to do after the fact.

Wdyt?

**Comment by graydon** [comment]
Possible. I think it might depend a bit on how larger-than-packed-u64 symbols / static slices work out.

**Comment by leighmcculloch** [comment]
That's a good point, I was only thinking about our existing u64 (Symbol) only keys.

But I think this issue can still happen independent of https://github.com/stellar/rs-soroban-env/issues/596. We can do https://github.com/stellar/rs-soroban-env/issues/596 first, and then evaluate if this is worth the tradeoff?

**Comment by leighmcculloch** [comment]
Closing because @graydon optimized structs using slices and linear memory copies. It isn't obvious to me whywe'd still do this given the new optimization we have.
