### ISSUE TITLE
Cannot have a contract with a type and method of the same name

### ISSUE THREAD

**Issue by paulbellamy** [stellar/rs-soroban-sdk#828]
For example, if the getter method in https://github.com/stellar/soroban-examples/blob/main/custom_types/src/lib.rs were named `state`, you'd get an error. This seems like a common pattern people would hit (especially with the 10char limit for method names).

**Comment by leighmcculloch** [comment]
The exact error looks like this:
```
error[E0428]: the name `__SPEC_XDR_STATE` is defined multiple times
  --> soroban-sdk/src/tests/contract_overlapping_type_fn_names.rs:12:1
   |
5  | #[contracttype]
   | --------------- previous definition of the value `__SPEC_XDR_STATE` here
...
12 | #[contractimpl]
   | ^^^^^^^^^^^^^^^ `__SPEC_XDR_STATE` redefined here
```
