### ISSUE TITLE
Deprecate with_source_account for a unified method

### ISSUE THREAD

**Issue by sisuresh** [stellar/rs-soroban-sdk#829]
### What problem does your feature solve?
There are two different methods used to call a contract with a simulated Invoker. The first is `with_source_account`, a method in the client that sets the Invoker to an `AccountID`. The second method is `as_contract`, an env which sets the invoker to a contract. It confusing to have these two methods live in different places when they're almost the same.

### What would you like to see?
Deprecate the methods specified above and replace with `with_invoker` which accepts `Into<Invoker>` and then add two impls `From<Account>` for Invoker and `From<BytesN<32>>` for Invoker (This is @leighmcculloch's idea from a [discord thread](https://discord.com/channels/897514728459468821/1063544780170219601/1064964331164418078)).

**Comment by graydon** [comment]
Sgtm, I'm putting this in backlog for @dmkozh since I _think_ it's in his wheelhouse. Feel free to reassign if that's wrong.

**Comment by dmkozh** [comment]
This is only relevant to the host testing now and there are not major inconsistencies there, so closing this.
