### ISSUE TITLE
Increase test coverage for `soroban-sdk`

### ISSUE THREAD

**Issue by jayz22** [stellar/rs-soroban-sdk#840]
### What problem does your feature solve?
Increase test coverage for `soroban-sdk`.
`soroban-sdk` provides building blocks for contracts. Increasing test coverage helps eliminating unexpected bugs (e.g. https://github.com/stellar/rs-soroban-sdk/pull/830 and https://github.com/stellar/rs-soroban-sdk/pull/827) before they occur. 

### What would you like to see?
Add more unit tests simliar to https://github.com/stellar/rs-soroban-sdk/pull/830 and https://github.com/stellar/rs-soroban-sdk/pull/827.
Currently most of the modules in `soroban-sdk` have limited / no unit tests. Yet, they are key building blocks for contracts which developers rely on. E.g. module `Vec`'s `push`, `pop`, `remove`, `get` are not covered by unit tests, similar problems exists for other modules such as `Map`, `Bytes`, `Set` etc. 
Too much of the sdk testing relies on integration tests or test contracts, which is limited in scope. Adding more unit tests helps eliminate unexpected bugs and reduces dependency on test contracts for bug finding.

**Comment by jayz22** [comment]
@Ray-Escobar That would be great, thanks for helping!

**Comment by Ray-Escobar** [comment]
Hi @jayz22 I have created various new test over some methods in Map, Bytes and Sets... I would like to continue onto other methods/modules but would first like to get some small feedback just to be sure everything is aligned, so will set up a PR soon. Does this sound good?

**Comment by jayz22** [comment]
@Ray-Escobar yes that sounds good!

**Comment by anupsdf** [comment]
Closing for now. Please re-open if this is important to have.
