### ISSUE TITLE
Use panic_with_error instead of panic in the token spec

### ISSUE THREAD

**Issue by sisuresh** [stellar/rs-soroban-sdk#844]
Related to https://github.com/stellar/soroban-examples/issues/199.

The token spec is meant to be use to generate a token client to call into token contract that implements the token spec. If a user uploads the token spec and tries to call into it, the contract will `panic!` with an error message, but that message won't propagate up because it isn't using `panic_with_error!`, making a simple bug difficult to debug.

**Comment by leighmcculloch** [comment]
We deprecated the token spec crate, so I think we can close this now.
