### ISSUE TITLE
Auth Next: Add try_ versions of auth methods

### ISSUE THREAD

**Issue by dmkozh** [stellar/rs-soroban-sdk#853]
Currently we always panic when `require_auth` call fails. It could be useful in some scenarios to gracefully handle the auth error, although before implementing this it would be nice to understand what are these cases.

**Comment by willemneal** [comment]
One use case that I currently have is I'm designing an `Owner` "riff", a composable piece that can be added to a contract to ensure that it has an owner.  It's a `owner_set` method will use auth.  It would be nice to have a owner::Error type which would return `Error::NotOwner`.

**Comment by leighmcculloch** [comment]
Independent of any specific reason or use case to support non-panic require auth calls:

A while ago we agreed that any function that a developer calls that panics, other than exceeding limits or gas, should be accompanied by a way for a developer to avoid the panic. Either by providing a way to detect if a panic would occur (e.g. `Vec` `get` function is accompanied by `Vec` `len`), or by providing a version of the function that performs the same operation but returns a `Result<>`.

The reason we made that call was because we're building an SDK that should enable developers to a variety of things we can't predict, and this is one simple pattern we can employ in the SDK to allow developers the freedom to do a variety of things.

**Comment by dmkozh** [comment]
> One use case that I currently have is I'm designing an Owner "riff", a composable piece that can be added to a contract to ensure that it has an owner. 

Details aside, would using a constructor solve this issue? I'm also curious as to what exactly does this have to do with `require_auth`; this seems like a simple storage check to me.

> A while ago we agreed that any function that a developer calls that panics, other than exceeding limits or gas, should be accompanied by a way for a developer to avoid the panic. 

It's a bit unfair to mention this in the context of auth next, as it hasn't been even discussed at that point. If the transaction signature or seq num is not correct the contract won't be executed at all. As auth next is a part of the host (== part of the core), I think the same logic can be applied as to other things that aren't directly managed by the contract and belong to the core/host.

> Independent of any specific reason or use case to support non-panic require auth calls:

I think it's quite important to understand the use case here in order to evaluate the cost/priority/usefulness tradeoff. We don't have infinite time and we need to prioritize the features in some fashion. There are features with a clear use case that we need to implement and I don't think we should prioritize anything that doesn't have any clear impact just to support something abstract/unknown.

The issue with graceful require_auth failure is that it might lead to the footguns on one hand (where the contract writer uses it incorrectly and allows unauthorized user to perform operations) and introduces significant implementation issues on the host side on the other hand. It's not clear how to preflight an authorization failure. If it's not possible to preflight it, the amount of things you can do is really limited. It's also not clear what should be the rollback behavior.

There also is really nothing that try_require_auth can achieve that can't be achieved now with the present tools. In general, if the address doesn't need to be authorized, just don't call `require_auth` for it. This will result in cheaper and safer code.

**Comment by dmkozh** [comment]
It doesn't seem like the need for this has come up during the months of Soroban auth usage and I stand by my arguments in the previous comment. We can reopen this if necessary (or maybe better come up with a less footgun-y solution), but for now I'll close this.
