### ISSUE TITLE
Catch dependency mismatches before merging

### ISSUE THREAD

**Issue by sisuresh** [stellar/rs-soroban-sdk#858]
We had a recent issue where the xdr ref was bumped, but env wasn't, resulting in two versions or the xdr crate being imported. This was caught downstream by the platform team and resulted in quite a bit of time wasted. We should look into catching this issue in a github action. Maybe scanning the Cargo.lock file for multiple versions of xdr,env,and sdk?

**Comment by graydon** [comment]
Yes, there are some cargo checks we can add to avoid duplicates. I'll take this.

**Comment by graydon** [comment]
Taking steps towards this in the env repo in https://github.com/stellar/rs-soroban-env/pull/740
Once working, same setup should be replicated in SDK repo at least, maybe others.

**Comment by graydon** [comment]
this is actually going to be a lot trickier than expected because of the number of duplicates we _want_ in the dual-version config.

**Comment by graydon** [comment]
Oh, wait, this is an SDK bug; I guess we can catch it in the SDK at least.

**Comment by graydon** [comment]
done in https://github.com/stellar/rs-soroban-sdk/pull/931
