### ISSUE TITLE
Support `Option` in `contracttype`

### ISSUE THREAD

**Issue by dmkozh** [stellar/rs-soroban-sdk#877]
We should allow using `Option` in UDT structs. Currently some necessary trait(s) are missing implementation, such as:

`the trait `From<&std::option::Option<i32>>` is not implemented for `stellar_xdr::ScVal`

There is seemingly no good reason to not support this, so we should implement the missing traits.

**Comment by Jenietoc** [comment]
Any approach to solve this? @dmkozh

**Comment by willemneal** [comment]
To get around it for now you can create your own Option type. Not optimal, but that's what I've done to get around this.

**Comment by Jenietoc** [comment]
Yes, we also opted to create our own Option type. I'm trying to solve this issue in the source code
