### ISSUE TITLE
Add u256/i256 and String types

### ISSUE THREAD

**Issue by willemneal** [stellar/rs-soroban-sdk#897]
### What problem does your feature solve?

Have parity with the new XDR types.

### What would you like to see?

First class support for types in the sdk.

**Comment by jayz22** [comment]
We already have the types `U256`, `I256` defined in `num.rs` and type `String` defined in `string.rs`. They currently only contain the definitions and a few basic conversions, as we are working on adding host functions supports for them. 
But for "parity with XDR types" purpose they already exist. Is this sufficient for what you need?
