### ISSUE TITLE
Bring back symbol!

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#927]
In https://github.com/stellar/rs-soroban-sdk/pull/879 the `symbol!` macro was replaced with `Symbol::short` for short integer forms of symbols and `Symbol::new` for larger host stored symbols.

Even though `Symbol::short` is a `const` function, there's no guarantee it will be executed at compile time and for most uses by contract developers, and most uses in generated code, the function logic will be embedded in the resulting .wasm file and the conversion from string to integer will occur at runtime.

This is the reason we originally added `symbol!` in https://github.com/stellar/rs-soroban-sdk/pull/488. We had discovered that `const` functions in Rust are preferred to be executed at runtime unless they are called within a `const` context. The `symbol!` macro ensured that the conversion occurred in a `const` context. Because the function does conversion of the string, if it is included in the .wasm for each call, that's ~50-200 bytes of extra wasm per call.

The macro was that was removed in #879 was as below:

```rust
#[proc_macro]
pub fn symbol(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as LitStr);
    match Symbol::try_from_str(&input.value()) {
        Ok(_) => quote! {{
            const symbol: soroban_sdk::Symbol = soroban_sdk::Symbol::from_str(#input);
            symbol
        }}
        .into(),
        Err(e) => Error::new(input.span(), format!("{}", e))
            .to_compile_error()
            .into(),
    }
}
```

Given that `Symbol`s can be short or long now, where the latter requires an `Env`, we need to rethink the macro rather than just copy and paste it back. Some ideas:

1. Add the macro back as it is, just for use with short symbols, and name it `symbol_short!`.

   ```rust
   // 🟢 
   symbol_short!("SHORT");
   
   // 🟢 
   Symbol::new(env, "LONGLONGLONG");
   
   // 🔴 with friendly compiler error
   symbol_short!("LONGLONGLONG");
   
   // 🤷🏻 
   Symbol::new(env, "SHORT");
   ```
   
2. Add a new macro `symbol!` that optionally takes an `Env` and does a compile-time const conversion if the `Symbol` is short enough, otherwise it uses the `Env`. In the event someone calls `symbol!` with a value too long without an `Env` it is trivial to display a user-friendly compiler error saying the `Env` is required for symbols over a certain length.

   ```rust
   // 🟢 
   symbol!("SHORT");
   
   // 🟢 
   symbol!(env, "LONGLONGLONG");
   
   // 🔴 with friendly compiler error
   symbol!("LONGLONGLONG");
   
   // 🤷🏻 
   symbol!(env, "SHORT");
   ```

I think (2) would be preferred as gives them one tool to use, and helps them use it the right way.

cc @graydon @dmkozh

**Comment by willemneal** [comment]
Could we also have something similar for string? And what is the difference for devs between the two?
