### ISSUE TITLE
Keccak256

### ISSUE THREAD

**Issue by cjcobb23** [stellar/rs-soroban-sdk#934]
Hi, would it be possible to add keccak256 support? Or maybe just provide some guidance about how one could do that themselves (or import a third party library even to compute a keccak256 hash)?

**Comment by leighmcculloch** [comment]
@cjcobb23 Thanks for opening this issue. This is something we're thinking about, and are tracking in the issue here: https://github.com/stellar/rs-soroban-env/issues/676. Please subscribe to that issue for updates and contribute there!
