### ISSUE TITLE
Auth: Remove nonce from mock auths

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#935]
The `mock_auths` function on `Env` and contract clients accepts a slice of `MockAuth` which include the parameters required to build a `xdr::ContractAuth`. One of those parameters is `nonce`.

https://github.com/stellar/rs-soroban-sdk/blob/ba764f3fab7a9c605dd683fa6f8702b688091d29/soroban-sdk/src/testutils/mock_auth.rs#L15-L19

@dmkozh pointed out in https://github.com/stellar/rs-soroban-sdk/pull/929#discussion_r1183138942 that the nonce is not particularly relevant to a developer. The reason is that nonce is more about ensuring a signature can only be used once, but when we mock auth we are mocking signature verification and so similar to why we don't need to explicitly state the signatures when mocking auth, we shouldn't need to state the nonce explicitly.

**Comment by leighmcculloch** [comment]
I looked into implementing this, but I found a case where if nonce was auto-calculated by the SDK that the SDK would be unable to correctly predict what the nonce value should be for the auth. 

To correctly predict the nonce for each auth the SDK needs to collect the nonces for all addresses that are being authorized. The first time an address is used will be assigned that nonce value. The second time an address is used will be assigned that nonce value plus one. And so on.

However, if a contract accepts two auths for the same address and intends to auth only one and not the other, and those invocations are separate `ContractAuth` trees with their own nonce, the auths will need to have the same nonce. The SDK cannot predict if `ContractAuth`s will be exhausted or not, and therefore can't predict if their nonces will be consumed impacting `ContractAuth`s that follow.

I wonder if https://github.com/stellar/rs-soroban-env/issues/655 will make it easier to remove nonce? Possibly because nonces are not sequential. The SDK would be able to assign random nonces.

There may still be issues with implementing this, but for the moment I'm marking this as:

Dependent on https://github.com/stellar/rs-soroban-env/issues/655.

**Comment by dmkozh** [comment]
Yeah, this scenario seems tricky for SDK (it's also tricky for the actual usage in core as well). With random nonces you won't need to make any assumptions about nonces being consumed or ordered, so that definitely would make generating them trivial.

**Comment by leighmcculloch** [comment]
@dmkozh I think you just recently did this, or had something in the works for it. Is that right?

**Comment by dmkozh** [comment]
Yeah, nonces are completely independent now and SDK just generates random numbers for mock auths.
