### ISSUE TITLE
Add a last() method for events and/or make all() iterable

### ISSUE THREAD

**Issue by esteblock** [stellar/rs-soroban-sdk#958]
While testing smart contracts with a lot of event being emitted, it's needed to test the last event emitted, or at least being able to iterate over them.
Currently I cannot do it.
Or there is something I am missing?

**Comment by leighmcculloch** [comment]
The type returned from `all()` is a `soroban_sdk::Vec` which has a [last](https://docs.rs/soroban-sdk/latest/soroban_sdk/struct.Vec.html#method.last) method, and can be iterated over if you call [iter](https://docs.rs/soroban-sdk/latest/soroban_sdk/struct.Vec.html#method.iter).

Would those methods work for you?

If not, could you share an example to make sure I'm understanding the context?

**Comment by esteblock** [comment]
Thanks! Sorry, I did some tests and I was founding the "Not an iterator", but I got confused.

I managed to do it as:

```let topics = (Symbol::new(&e, "deposit"), user.clone(), 100_i128);
    let events_vec = e.events().all();
    let last_event = events_vec.last().unwrap().unwrap();

    assert_eq!(
        vec![&e, last_event],
        vec![
            &e,
            (   liqpool.contract_id.clone(),
                topics.into_val(&e),
                100_i128.into_val(&e)),
        ]
    );
```

**Comment by leighmcculloch** [comment]
I just tried this and it worked:
```rust
for e in env.events().all() {
    std::println!("my event {:?}", e);
}
```

In the code snippet you shared it should be possible to `assert_eq!` on the individual event too, without the additional vecs:

```rust
assert_eq!(
    last_event,
    (
        liqpool.contract_id.clone(),
        topics.into_val(&e),
        100_i128.into_val(&e)
    ),
);
```

**Comment by esteblock** [comment]
Yes, thanks!
