### ISSUE TITLE
Token SDK could use "in-place" documentation

### ISSUE THREAD

**Issue by ElliotFriend** [stellar/rs-soroban-sdk#966]
### What problem does your feature solve?

A developer without a background in EVM or smart contracts in general can be easily confused by the existing interface documentation for the SAC (i.e., `from`, `spender`, `allowance`, etc. may not have much context or meaning to them).

Additionally, between the `soroban-docs` site, and the SDK documentation there are different levels of information, when a "unified" set of descriptions could be useful in both places. Having this information "originate" in the source code and then copied into the documentation elsewhere seems like the ideal way to designate the SDK repo as the "canonical" source for it.

### What would you like to see?

Following a brief (old-ish) conversation in Slack, the Token interface code could use some "doc comments" to make it feel a bit more informative. We don't have to dive into the nitty-gritty and detailed descriptions of vocabulary (that's probably more fitting for the docs site, anyway). But a fuller description of the arguments each function expects could greatly improve usability.

### What alternatives are there?

Not exactly sure. Here are some guesses?

- Keep the existing documentation fragmented between docs-site, source code, etc.
- Have the interface documentation live solely in the SDK?
- Have the interface documentation live solely in the docs-site?

**Comment by tomerweller** [comment]
I think that documentation in-place in the sdk would be great, but is not sufficient. We also need:
 
1. A technical token Interface SEP. We haven't really started creating Soroban SEPs but we need to start and none is more important than the token one. This should probably look like the [official erc20 doc](https://eips.ethereum.org/EIPS/eip-20) adapted to Soroban and the SEP format. 
2. A more user friendly doc that explains all the token interface concepts. something like [this](https://ethereum.org/en/developers/docs/standards/tokens/erc-20/)

**Comment by ElliotFriend** [comment]
> documentation in-place in the sdk would be great, but is not sufficient

As an initial effort, I copied some of what lives in the [Token Interface] page in the docs-site, with expanded definitions and explanations of the arguments and stuff. The PR is here: #967 

> 1. A technical token Interface SEP. We haven't really started creating Soroban SEPs but we need to start and none is more important than the token one. This should probably look like the [official erc20 doc](https://eips.ethereum.org/EIPS/eip-20) adapted to Soroban and the SEP format.

Would this be different than [CAP-46-6](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0046-06.md)? Perhaps I don't fully get the CAP/SEP difference, though. CAPs seem to be more about the protocol-level XDR/consensus stuff? And SEPs are more like "how to implement it"?

> 2. A more user friendly doc that explains all the token interface concepts. something like [this](https://ethereum.org/en/developers/docs/standards/tokens/erc-20/)

Is this maybe where the existing [Token Interface] page could fit in? It seems like that's _kindof_ what it's trying to do? Might need some updating/re-thinking to have it really fit that need, though.

[Token Interface]: https://soroban.stellar.org/docs/reference/interfaces/token-interface

**Comment by tomerweller** [comment]
> Perhaps I don't fully get the CAP/SEP difference, though. CAPs seem to be more about the protocol-level XDR/consensus stuff

CAPs are changes to the core protocol and software (keep in mind that soroban-env is part of that). SEPs are standards and protocols that the ecosystem can adopt (but are not forced to). 

> Would this be different than [CAP-46-6](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0046-06.md)?

Yes. This is a unique situation in which a CAP is implementing a standard that is defined (or should be, once we writ it down) in a SEP. The SAC implements the standard token interface but is part of the core protocol. 

> Is this maybe where the existing [Token Interface](https://soroban.stellar.org/docs/reference/interfaces/token-interface) page could fit in

Yup! I think this makes sense and we can use the ethereum page as an example for how to thicken this up

**Comment by leighmcculloch** [comment]
We have [SEP-41] that details the token interface.

[SEP-41]: https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0041.md

**Comment by leighmcculloch** [comment]
Some inline doc improvements in:
- https://github.com/stellar/rs-soroban-sdk/pull/1247
