### ISSUE TITLE
Follow ups to v0.8.5 and TypeScript Gen

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#968]
We should plan a couple follow up tasks to #871:

- [ ] This change needs opening against `main`. We won't commit a merge commit of `release/v0.8.5` into `main` because we don't use merge commits in this repository. Someone can open a merge as a PR then we'll squash and merge that commit into `main`. Or take the code straight to its own crate in soroban-tools, `soroban-spec-typescript`.
- [ ] Remove the dependence on the JSON types so that conversion from XDR spec to typescript is `ScSpecEntry` -> TypeScript, and not `ScSpecEntry` -> JSON -> TypeScript. Why: For the reasons mentioned at https://github.com/stellar/rs-soroban-sdk/pull/871#discussion_r1213585760, https://github.com/stellar/rs-soroban-sdk/pull/871#discussion_r1213584250, and https://github.com/stellar/rs-soroban-sdk/pull/871#pullrequestreview-1462963564.

- [x] Break up the `soroban-spec` crate into `soroban-spec`, `soroban-spec-rust`, `soroban-spec-json`. (And subseqneutly the typescript generator would go into a `soroban-spec-typescript` either here or in soroban-tools.). Why: Having typescript dependencies in the soroban-sdk repo is going to make development here pretty complex, and ultimately the typescript generation code needs a unique set of reviewers/owners who are different to those of the rest of the code here. We can house the `soroban-spec-typescript` crate in the `soroban-tools` repo.

cc @paulbellamy @tsachiherman @willemneal @chadoh

_Originally posted by @leighmcculloch in https://github.com/stellar/rs-soroban-sdk/issues/871#issuecomment-1587906728_

**Comment by leighmcculloch** [comment]
For the second task I've reserved the crates: `soroban-spec-rust`, `soroban-spec-json`, `soroban-spec-typescript`.

**Comment by paulbellamy** [comment]
The crate break-up sounds kind of onerous, tbh. Particularly having some of them live in soroban-tools feels very... circular. Specifically, the `cli (tools) -> sdk (sdk) -> spec (sdk) ->  spec-typescript (tools)` dependency chain. Seems like it will introduce more x-repo dependency chaining friction and pain.

**Comment by willemneal** [comment]
So we should have one monorepo?

**Comment by leighmcculloch** [comment]
> Particularly having some of them live in soroban-tools feels very... circular. Specifically, the `cli (tools) -> sdk (sdk) -> spec (sdk) -> spec-typescript (tools)` dependency chain

No circular dependency would exist. The CLI would be dependent on spec rust, spec json, and spec typescript. spec would not be dependent on spec typescript.

**Comment by willemneal** [comment]
Good point, `soroban-spec` only relies on `stellar-xdr`. I do, however, wonder if it is worth pulling the bindings stuff out of the core CLI and into a plugin.  This would allow for a independent release schedules.

**Comment by leighmcculloch** [comment]
> The crate break-up sounds kind of onerous...Seems like it will introduce even more x-repo dependency chaining friction and pain.

We could simplify the number of crates by only breaking out the typescript gen, but I think the typescript needs to live elsewhere. The code for it doesn't really belong in this repo as the reviewers for this repo are not maintaining it. The same could be said for the json generator too, it is not relevant to the reviewers of this repo. The rust implementation however is maintained by the folks in this repo.

We could put the crates in their own repo, but that sounds more onerous, where-as moving the json and typescript crates into the soroban-tools repo moves them to the folks who use and maintain them, and adds zero burden to the release process because of workplace dependencies and our release process releasing all crates in the repo.

**Comment by leighmcculloch** [comment]
I've opened the following changes which are trivial:
- https://github.com/stellar/rs-soroban-sdk/pull/972
- https://github.com/stellar/rs-soroban-sdk/pull/973

When we reapply the typescript change to main it should be trivial to apply it in a new crate, either here, or in soroban-tools.

**Comment by leighmcculloch** [comment]
Closing because I think the first task, which was the most important follow up, is no longer relevant because the crates simply moved to the soroban-tools repo.
