### ISSUE TITLE
Support View/Read-Only Functions

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#971]

**Comment by leighmcculloch** [comment]
I spent sometime looking into how we could implement view functions, because it sounded like it would be helpful for tooling if tooling could know statically if contract functions were executable without affecting state change. This is a summary of what I found.

View functions are a feature of Solidity, where you can mark a function using the `view` keyword and the compiler will guarantee that the function does not modify ledger state in anyway. This prevents the function from storing data, emitting events, creating contracts. In Solidity the feature is first class and really clear, with the use of the `view` keyword directly on a function.


1️⃣ The first thing we could do is allow developers to simply mark their functions as read-only using a macro attribute that the `contractimpl` macro picks up. This is relatively trivial to do. The XDR contract interface embedded in the contract would have a flag on functions set if that attribute was used. It would however be really easy to break the promise made by the attribute by storing data, emitting events, or calling another contract that does that.

Given we're using Rust, developers have some expectation that the compiler only lets them do valid things, especially when it comes to mutability vs immutability, and a read-only function is basically an immutable function.

2️⃣ Rust has no concept of a "read-only" function, but we could have the compiler help us enforce a read-only state by giving read-only functions a read-only `Env`, or rather a `&Env`. Read-write functions would be given a `&mut Env`.

Supporting this would be relatively simple initially by:
- Making two `Storage` types, one for read-only operations, and one for both read and write operations.
- Changing all `Env` functions that result in write operations to require a `&mut self`.

3️⃣ The last part which requires a bit of work is that generated clients for Rust need to be two clients. Each contract needs a client for read-only functions only, and another client for read-write functions. The read-only client would require a `&Env`, and the read-write client would require a `&mut Env`.

All of the above is doable, however it increases the cognitive load of the developer as they need to navigate multiple clients for other contracts, so we should only do it if there's a significant benefit.

Invocations of Soroban contract functions are always accompanied by a footprint that contains read-only and read-write data sets. The simulation feature of the Soroban RPC allows a developer to find out what the footprint is, as well as what events would be emitted, for the entire call stack. In many ways this allows tooling already to identify read only functions dynamically, even in cases when a function may sometimes be read-only and sometimes read-write.

Given the above it doesn't yet seem critical that we add view functions and I plan to close this issue for now.

Before I do, do folks see cases where having statically known read-only functions would be very useful?

**Comment by mootz12** [comment]
The argument for read-only functions is that contract developers can be sure some downstream call doesn't write any data, as this needs to be known statically. While I don't have any strong use-cases as for why this would be needed off the top of my head, I definitely can see how this might be something comforting to catch for developers at compile time.

From a dApp / downstream perspective, the footprint is a much better tool.

That being said, if this was pursued, I would be in favor of seeing option `2` implemented.

**Comment by earrietadev** [comment]
In my opinion the only reason I would like to have it would be "mental peace" that a function didn't update something by mistake (basically just helping the developer) but this is not that big of a deal we could say because we could also just test it instead...

Now, something I do like about view functions on other chains is that they do not cost gas if called externally which we could say is the safest way to get the state of something in the contract... But I remember I read somewhere that we don't want to push people to do that because it could saturate the chain and that we already have the simulation process instead

**Comment by leighmcculloch** [comment]
> What I definitely _do_ think we need is the ability to call a footprint-only via the CLI (if this doesn't yet exist).

@tyvdh We have an issue still open for this: https://github.com/stellar/soroban-tools/issues/225. I believe we also discussed the possibility of there being options on invoke so you could simulate only even in cases that are read-write.

**Comment by leighmcculloch** [comment]
Another option, 5️⃣, is that we allow cross contract invocation to specify if writes are allowed or not as an option that is default on. This is probably simpler to understand from a user perspective.

**Comment by leighmcculloch** [comment]
> Now, something I do like about view functions on other chains is that they do not cost gas if called externally which we could say is the safest way to get the state of something in the contract... But I remember I read somewhere that we don't want to push people to do that because it could saturate the chain and that we already have the simulation process instead

@earrietadev Once https://github.com/stellar/soroban-tools/issues/225 is implemented calling any function, whether it's a view function or not, will be able to be free by bailing after simulation. Do you think that will satisfy the need?

**Comment by leighmcculloch** [comment]
Closing since benefit to cost ratio doesn't make this particularly compelling, and to @tyvdh's point Soroban has a different seat of features in simulation.

If anyone wishes to make a point in favor of adding them, please continue to do so and this issue can be reopened at that time.

**Comment by leighmcculloch** [comment]
Started a protocol discussion thread on this topic here:
- https://github.com/stellar/stellar-protocol/discussions/1454
