### ISSUE TITLE
Add support for keccak

### ISSUE THREAD

**Issue by HariSeldon23** [stellar/rs-soroban-sdk#986]
### What problem does your feature solve?
It allows for much easier interchain applications. Considering EVM chains use keccak it would greatly facilitate optimistic messaging systems.

### What would you like to see?
Support for keccak hashing in smart contracts.

### What alternatives are there?
Blake2 would also be nice if we wanted to design interchain messaging for Cardano and Polkadot

**Comment by masonforest** [comment]
I just opened a PR for this: [Expose secp256k1 and keccak256 in the SDK](https://github.com/stellar/rs-soroban-sdk/pull/1028)

**Comment by HariSeldon23** [comment]
Cool, will close this and track changes there.

Thanks!
