### ISSUE TITLE
Add get_many and similar bulk operations to collections

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#997]
In response to the discussion at:
- https://github.com/stellar/rs-soroban-env/issues/696

We should make it easier for folks using the SDK to perform bulk read / write operations on the collection types, `Vec` and `Map`. Bulk complete read/writes are already possible on the `Bytes` type, but we should probably align all collections to be similar and add partial bulk read/writes there too.

The idea is to follow the existing pattern in the Rust stdlib for bulk reads, by providing functions like `get_many` that return an array containing a fixed number of items.

**Comment by leighmcculloch** [comment]
@graydon I'm thinking of implementing it like this:
- https://github.com/stellar/rs-soroban-sdk/pull/998

My thoughts are we don't need this for all types of access. We don't need `try_` variants, or the non-`_unchecked` variants. Folks needing to do the safest thing should probably use the other functions. My main reason for that though is avoiding dealing with current Rust's limitations in initialization arrays without `Default` impls. So it's not the best reason, but maybe as a starting point this would be sufficient?

**Comment by leighmcculloch** [comment]
Currently thinking it would be sufficient to add the following functions:
- `Vec`
   - `get_many_unchecked`
   - `set_many`
   - `remove_many_unchecked` - maybe not worth it?
   - `push_front_many`
   - `pop_front_many`
   - `push_back_many`
   - `pop_back_many`
- `Map`
   - `get_many`
   - `set_many`
   - `remove_many` - maybe not worth it?

@graydon wdyt?

Each of the above needs a new host function that does a linear memory copy of the RawVals.

**Comment by graydon** [comment]
I think we can wait on this until there's evidence it's a bottleneck for anyone.

**Comment by leighmcculloch** [comment]
👍🏻 Then I think I'll close it. We can reopen it when that shows up.
